import QuantumBlockEncoding.PrimitiveBasisLE

-- Whole current module signature and axiom audit; not an additional theorem.
#check @QuantumBlockEncoding.primitiveBasisLEEquiv
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_zero_apply
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_zero_apply
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_succ_value
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_succ_value
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_six_value
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_six_value
#check @QuantumBlockEncoding.primitiveBits2LE
#print axioms QuantumBlockEncoding.primitiveBits2LE
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_wire_zero
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_wire_zero
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_wire_one
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_wire_one
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_0
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_0
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_1
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_1
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_2
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_2
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_3
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_two_symm_3
#check @QuantumBlockEncoding.primitiveBits2LEWithout
#print axioms QuantumBlockEncoding.primitiveBits2LEWithout
#check @QuantumBlockEncoding.primitiveBits2LEGridWithout
#print axioms QuantumBlockEncoding.primitiveBits2LEGridWithout
#check @QuantumBlockEncoding.splitPrimitiveWire_primitiveBits2LE_context_eq
#print axioms QuantumBlockEncoding.splitPrimitiveWire_primitiveBits2LE_context_eq
#check @QuantumBlockEncoding.splitPrimitiveWire_primitiveBasisLEEquiv_two_symm_context_eq
#print axioms QuantumBlockEncoding.splitPrimitiveWire_primitiveBasisLEEquiv_two_symm_context_eq
#check @QuantumBlockEncoding.primitiveBits3LE
#print axioms QuantumBlockEncoding.primitiveBits3LE
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_wire_zero
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_wire_zero
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_wire_one
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_wire_one
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_wire_two
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_wire_two
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_0
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_0
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_1
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_1
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_2
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_2
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_3
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_3
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_4
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_4
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_5
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_5
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_6
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_6
#check @QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_7
#print axioms QuantumBlockEncoding.primitiveBasisLEEquiv_three_symm_7
#check @QuantumBlockEncoding.primitiveBits3LEWithout
#print axioms QuantumBlockEncoding.primitiveBits3LEWithout
#check @QuantumBlockEncoding.primitiveBits3LEGridWithout
#print axioms QuantumBlockEncoding.primitiveBits3LEGridWithout
#check @QuantumBlockEncoding.splitPrimitiveWire_primitiveBits3LE_context_eq
#print axioms QuantumBlockEncoding.splitPrimitiveWire_primitiveBits3LE_context_eq
#check @QuantumBlockEncoding.splitPrimitiveWire_primitiveBasisLEEquiv_three_symm_context_eq
#print axioms QuantumBlockEncoding.splitPrimitiveWire_primitiveBasisLEEquiv_three_symm_context_eq
