import QuantumBlockEncoding
import Verso
import VersoManual
import VersoBlueprint

open Verso.Genre
open Verso.Genre.Manual
open Informal

set_option linter.hashCommand false
set_option linter.style.longLine false
set_option verso.blueprint.externalCode.strictResolve true

#doc (Manual) "Overview: from a user target to a Lean certificate" =>
%%%
file := "overview"
%%%

ABEIS begins with either a normalized target state or an operator together with its access model.
It does not identify a plausible circuit with a proof. The library separates the requested
mathematical object, a candidate implementation, the semantic proof, and the resource record.

:::definition "state-preparation target" (lean := "QuantumBlockEncoding.StatePreparationTarget")
For $`n` qubits, a state-preparation target stores amplitudes indexed by
$$`\operatorname{Fin}(2^n)` and an explicit normalization proposition. The source field records
where the target came from; it is metadata and cannot replace the normalization proof.
:::

:::definition "verified state preparation" (lean := "QuantumBlockEncoding.VerifiedStatePreparation") (uses := "state-preparation target")
A state-preparation candidate supplies a matrix, a circuit transcript, a schedule, resources, and
a unitarity proposition. Promotion to a verified certificate requires proofs of normalization,
unitarity, and first-column equality. Thus the user-level condition is
$$`U|0^n\rangle=|\psi\rangle.`
:::

:::definition "operator query target" (lean := "QuantumBlockEncoding.QueryOperatorTarget")
An operator task records a finite matrix $`A`, a normalizer $`\alpha`, its provenance, its semantic
contract, and any free parameters. The access model and normalization remain visible inputs rather
than hidden assumptions.
:::

:::definition "operator block-encoding candidate" (lean := "QuantumBlockEncoding.OperatorBlockEncodingCandidate") (uses := "operator query target")
For an $`n`-qubit target and $`a` auxiliaries, the candidate matrix acts on $`2^{n+a}` dimensions.
It carries the register layout, circuit, schedule, resource count, and two separate propositions:
unitarity and containment of the normalized target in the selected block.
:::

:::definition "verified operator block encoding" (lean := "QuantumBlockEncoding.VerifiedOperatorBlockEncoding") (uses := "operator block-encoding candidate")
The verified record contains proofs of the candidate's unitarity and block predicate. It is the
smallest user-facing certificate that closes both semantic leaves. A clean-block-only package is a
reusable intermediate result, not automatically this full certificate.
:::

:::definition "resource score" (lean := "QuantumBlockEncoding.BlockEncodingCost")
Candidates at the same semantic tier are compared lexicographically by gate count, circuit depth,
auxiliary qubits, and unresolved oracle calls. Normalizer quality and proof status are assessed
before this concrete score.
:::

:::theorem "exact certificates enter approximate search at zero error" (lean := "QuantumBlockEncoding.VerifiedOperatorBlockEncoding.asZeroErrorApprox") (uses := "verified operator block encoding")
When the approximate backend uses exact block containment as its zero-error proposition, every
verified exact certificate can seed approximate search with $`\varepsilon=0`. This is an adapter,
not a claim about an unstated operator norm.
:::

# Documentation coverage

The catalog is regenerated by scripts/generate-blueprint-catalog.py. Its committed JSON audit
counts every explicit public definition, abbreviation, opaque declaration, inductive type,
structure, class, theorem, and lemma in the Lean source. Private implementation lemmas are counted
as deliberate exclusions. Structure-generated projections are accessible through their parent
structure but are not double-counted as source declarations.

The default library modules are expected to build without open proofs. RobinMatrix.lean is an
optional historical research module with two explicitly visible sorry-guarded diagnostics; it has
its own catalog chapter so its status cannot be confused with the certified public surface.
