import QuantumBlockEncoding.Circuit

/-!
# Block-encoding certificates

The paper's main issue is that an "oracle exists" statement is not enough for a
real quantum computer.  This file records the data that must ultimately be
certified: a matrix target, a circuit, normalization, ancilla layout, and proof
obligations for unitarity and block correctness.
-/

namespace QuantumBlockEncoding

structure RegisterLayout where
  systemQubits : Nat
  signalQubits : Nat
  pureAncillas : Nat
deriving Repr, DecidableEq

/-- A block-encoding candidate before semantic proofs are attached. -/
structure BlockEncodingSpec (α : Type u) (rows cols : Nat) where
  matrix : Matrix rows cols α
  normalizer : α
  error : α
  layout : RegisterLayout
  circuit : Circuit
  resource : Resource

/--
A verified block encoding.  The three proposition fields are intentionally
parameters of the certificate so that early project files can state workflows
without committing to a specific matrix norm or unitary semantics.  A mathlib
backend should instantiate these propositions with concrete definitions.
-/
structure VerifiedBlockEncoding (α : Type u) (rows cols : Nat) where
  spec : BlockEncodingSpec α rows cols
  isUnitary : Prop
  blockCorrect : Prop
  resourceBound : Prop
  unitaryProof : isUnitary
  blockProof : blockCorrect
  resourceProof : resourceBound

namespace VerifiedBlockEncoding

theorem unitary {α : Type u} {rows cols : Nat}
    (v : VerifiedBlockEncoding α rows cols) : v.isUnitary :=
  v.unitaryProof

theorem correct {α : Type u} {rows cols : Nat}
    (v : VerifiedBlockEncoding α rows cols) : v.blockCorrect :=
  v.blockProof

theorem resource_ok {α : Type u} {rows cols : Nat}
    (v : VerifiedBlockEncoding α rows cols) : v.resourceBound :=
  v.resourceProof

end VerifiedBlockEncoding

/-- A high-level construction claim imported from a paper or generated by AI. -/
structure ConstructionClaim where
  name : String
  source : String
  target : String
  normalization : String
  layout : String
  resource : AsymptoticResource
deriving Repr, DecidableEq

end QuantumBlockEncoding
