import QuantumBlockEncoding.GHL2025

/-!
# Open problem registry

The style is inspired by `teorth/optimizationproblems`: each problem has a
stable id, a crisp acceptance test, and a verification target.  The subject
matter is block-encoding and oracle construction rather than numerical bounds.
-/

namespace QuantumBlockEncoding

inductive ProblemStatus where
  | open
  | inProgress
  | formalized
deriving Repr, DecidableEq

structure OpenProblem where
  id : String
  title : String
  status : ProblemStatus
  statement : String
  acceptanceTest : String
  references : List String
deriving Repr, DecidableEq

def openProblems : List OpenProblem :=
  [
    {
      id := "QBE-001",
      title := "Gate-level Robin derivative block encoding for arbitrary stencil",
      status := ProblemStatus.open,
      statement := "Given a finite-difference stencil and Robin boundary data, synthesize the bulk-plus-boundary circuit for D and prove its block-encoding normalization.",
      acceptanceTest := "A Lean VerifiedBlockEncoding whose concrete matrix semantics equal the requested derivative matrix and whose resource bound is O(kappa*n) plus coefficient-oracle cost.",
      references := ["Guseynov-Huang-Liu 2025, one-term Robin theorem"]
    },
    {
      id := "QBE-002",
      title := "Nonseparable multivariate amplitude oracle",
      status := ProblemStatus.open,
      statement := "Construct efficient amplitude block encodings for multivariate piecewise polynomial coefficient functions beyond sums of separable factors.",
      acceptanceTest := "A Lean construction that takes a multivariate polynomial certificate and returns a block encoding with explicit normalization and gate count.",
      references := ["Guseynov-Huang-Liu 2025, multidimensional oracle section", "Gilyen et al. 2019 PET/QSVT"]
    },
    {
      id := "QBE-003",
      title := "Normalization optimization for PDE Hamiltonians",
      status := ProblemStatus.open,
      statement := "Reduce or certify optimality of the alpha factor in block encodings of H, especially the derivative-order factor 2^(p*n).",
      acceptanceTest := "A Lean theorem comparing two candidate constructions and proving a smaller normalization or a lower bound.",
      references := ["Guseynov-Huang-Liu 2025, Remark on ||H||_max"]
    },
    {
      id := "QBE-004",
      title := "Pure-ancilla reuse certificates",
      status := ProblemStatus.open,
      statement := "Prove that generated comparator, multi-control, and sparse-access subcircuits return work qubits to |0>.",
      acceptanceTest := "Gate-semantics proofs for each reusable ancilla register in the circuit IR.",
      references := ["Guseynov-Huang-Liu 2025, Appendix pure ancilla and multi-control"]
    },
    {
      id := "QBE-005",
      title := "QSVT phase-factor certificate pipeline",
      status := ProblemStatus.open,
      statement := "Attach rigorous Lean error certificates to phase factors generated by numerical QSP/QSVT solvers.",
      acceptanceTest := "A checker that imports phase factors and proves the requested polynomial approximation error.",
      references := ["Guseynov-Huang-Liu 2025, Hamiltonian simulation theorem"]
    },
    {
      id := "QBE-006",
      title := "Discrete Schrodingerisation clock error",
      status := ProblemStatus.open,
      statement := "Formalize the error from replacing the clock delta by a squeezed Gaussian and from tracing out the clock register.",
      acceptanceTest := "A Lean theorem bounding the trace-norm or observable error in terms of sigma and Richardson order.",
      references := ["Cao et al. time-dependent Hamiltonian embedding", "Guseynov-Huang-Liu 2025, Schrodingerisation section"]
    },
    {
      id := "QBE-007",
      title := "Graph-to-circuit matrix construction search",
      status := ProblemStatus.open,
      statement := "Use graph descriptions of sparse matrices to search for block-encoding circuits and verify the discovered construction in Lean.",
      acceptanceTest := "A reproducible search artifact plus a Lean certificate linking graph edges to matrix entries and gates.",
      references := ["Project motivation", "teorth/optimizationproblems registry style"]
    }
  ]

def problemCount : Nat := openProblems.length

end QuantumBlockEncoding
