import QuantumBlockEncoding.MultiControlledXScheduleSemantics
import QuantumBlockEncoding.MultiControlledXLayerSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRankCertificate
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaAlgorithmSchedule
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaAlgorithmBaseSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaMappedRecursiveTargetSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaTargetSupport
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaStageNoninterference
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaOuterSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaOuterIndexCoverage
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaOuterCaseSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaSourceCaseClassification
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaSelectedOrder
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaSelectedMembershipGeometry
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRecursiveControlGeometry
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRecursiveEndpointArithmetic
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRecursiveEndpointGeometry
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRecursiveTargetExclusion
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRecursiveStageExclusionSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaSpecialTailActivation
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaIntervalFactorization
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaFirstIntervalNoninterference
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaOrdinaryActivationFactors
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaOrdinaryChildActivation
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaStrictInteriorNoninterference
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaStrictInteriorStageInvariance
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaCancellationAlgebra
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaAlgorithmSemantics

/-!
# Admission entry point: Remaud--Vandaele Algorithm 2 semantic frontier

This import-only module checks the current proof DAG from exact physical `X'`
and `alpha'` rank through the source-facing Equation-(7) case decomposition.

The generic MCX layer, exact `X'`/`alpha'` rank chain, actual outer walls, and
the recursive proof-bearing schedule are compiler-verified. The schedule uses
target count as a strict well-founded measure and satisfies the paper's exact
gate/depth recurrences.

The semantic layer has now been normalized around Lean 4.29's dependent
`Decidable` behavior: MCX target actions use explicit activation cases; wall
slot equalities are transported with `simp` rather than dependent `rw`; wall
activation stability uses explicit `List.mem_ofFn'` witnesses; and the
ordinary/special target cases transport activation equivalences without
rewriting the proposition beneath an `ite`. The `C_L`-versus-`X'` proof reuses
the verified recursive-target exclusion layer rather than duplicating tail
arithmetic.

The next compiler frontier is therefore the actual Equation-(7) semantic DAG:
source-case coverage, selected-register geometry, recursive target exclusions,
ordinary/special activation geometry, stagewise invariance, cancellation, and
the final strong induction.
-/

namespace QuantumBlockEncoding
namespace RemaudVandaeleLadderAlphaSemanticFrontier

theorem admitted_frontier_marker : True := by trivial

end RemaudVandaeleLadderAlphaSemanticFrontier
end QuantumBlockEncoding
