import QuantumBlockEncoding.MultiControlledXScheduleSemantics
import QuantumBlockEncoding.MultiControlledXLayerSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRankCertificate
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaAlgorithmSchedule
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaAlgorithmBaseSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaMappedRecursiveTargetSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaTargetSupport
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaStageNoninterference
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaOuterSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaOuterIndexCoverage
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaOuterCaseSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaSourceCaseClassification
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaSelectedOrder
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaSelectedMembershipGeometry
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRecursiveControlGeometry
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRecursiveEndpointArithmetic
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRecursiveEndpointGeometry
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRecursiveTargetExclusion
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaRecursiveStageExclusionSemantics
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaSpecialTailActivation
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaIntervalFactorization
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaFirstIntervalNoninterference
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaOrdinaryActivationFactors
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaOrdinaryChildActivation
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaStrictInteriorNoninterference
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaStrictInteriorStageInvariance
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaCancellationAlgebra
import QuantumBlockEncoding.RemaudVandaeleLadderAlphaAlgorithmSemantics

/-!
# Admission entry point: Remaud--Vandaele Algorithm 2 semantic frontier

This import-only module checks the current proof DAG from exact physical `X'`
and `alpha'` rank through the source-facing Equation-(7) case decomposition.

The exact rank/canonical-child layer is now compiler-verified.  The outer-wall
schedule uses the repository's proof-bearing layer-count depth semantics
explicitly: `oneLayer` has schedule depth one, even when its gate list is empty,
while Algorithm 2 only instantiates the walls in its recursive branch.  Above
the schedule, the frontier separates the child induction hypothesis from left
wall noninterference by checking a generic mapped-child target-action theorem,
then continues through target support, source-index classification,
outer/recursive exclusions, ordinary/special activation geometry, stagewise
strict-interior invariance, and the local cancellation algebra.
-/

namespace QuantumBlockEncoding
namespace RemaudVandaeleLadderAlphaSemanticFrontier

theorem admitted_frontier_marker : True := by trivial

end RemaudVandaeleLadderAlphaSemanticFrontier
end QuantumBlockEncoding
