import QuantumBlockEncoding.HermiteBernstein
import QuantumBlockEncoding.StoredTensorTrain
import Mathlib.Data.Nat.Choose.Cast

/-!
# Materialized source Hermite Bernstein coefficients

The factorial table, source-series coefficients, and left-endpoint Bernstein
coefficients are each produced once and cached. Binomial coefficients are
evaluated from the stored real factorials, never by recursive Pascal calls.
Every real arithmetic operation and table access is charged in `StoredGivens`.
Natural-index manipulation and proof/counter bookkeeping are outside that
exact-real counter model; this is not finite-bit or full-machine complexity.

`fromConstant` takes one explicitly supplied scalar. `compile` supplies it by
one separately counted exponential primitive; it does not disguise `exp` as
trigonometry or make that transcendental call free.
-/

namespace QuantumBlockEncoding.StoredHermiteCoefficients

open scoped BigOperators
open StoredGivens HermiteBernstein
open StoredTensorTrain (sumEntries sumEntries_value sumEntries_cost_le)

structure FactorialTable (n : ℕ) where
  values : Vector ℝ (n + 1)
  next : ℝ

/-- Full-copy table extension, including one index comparison per output. -/
def extend {n : ℕ} (xs : Vector ℝ (n + 1)) (last : ℝ) : Run (Vector ℝ (n + 2)) :=
  collect fun i =>
    let result := if h : i.val < n + 1 then StoredGivens.read xs ⟨i.val, h⟩ else pure last
    ⟨result.value, tick .compare + result.cost⟩

theorem extend_value {n : ℕ} (xs : Vector ℝ (n + 1)) (last : ℝ) (i : Fin (n + 2)) :
    (extend xs last).value[i.val] = if h : i.val < n + 1 then xs[i.val] else last := by
  simp only [extend, collect_value]
  split <;> rfl

/-- The next integer multiplier is itself generated by a charged addition. -/
noncomputable def factorials : (n : ℕ) → Run (FactorialTable n)
  | 0 => do
      let values ← collect (fun _ : Fin 1 => pure (1 : ℝ))
      pure ⟨values, 1⟩
  | n + 1 => do
      let previous ← factorials n
      let last ← StoredGivens.read previous.values (Fin.last n)
      let value ← StoredGivens.mul previous.next last
      let next ← StoredGivens.add previous.next 1
      let values ← extend previous.values value
      pure ⟨values, next⟩

theorem factorials_next (n : ℕ) : (factorials n).value.next = (n + 1 : ℕ) := by
  induction n with
  | zero => simp [factorials, bind, pure, Run.bind, Run.pure]
  | succ n ih =>
      simp only [factorials, bind, pure, Run.bind, Run.pure, StoredGivens.add,
        charge, ih, Nat.cast_add, Nat.cast_one]

theorem factorials_value (n : ℕ) (i : Fin (n + 1)) :
    (factorials n).value.values[i.val] = (i.val.factorial : ℝ) := by
  induction n with
  | zero =>
      have eq : i = 0 := Fin.eq_zero i
      subst i
      simp [factorials, bind, pure, Run.bind, Run.pure, collect]
  | succ n ih =>
      simp only [factorials, bind, pure, Run.bind, Run.pure, StoredGivens.read,
        StoredGivens.mul, charge, extend_value]
      split_ifs with h
      · exact ih ⟨i.val, h⟩
      · have hi : i.val = n + 1 := by omega
        rw [factorials_next, ih (Fin.last n), hi, Nat.factorial_succ]
        simp

/-- `choose` uses three cached factorial entries and two field operations. -/
noncomputable def chooseFrom {N : ℕ} (F : Vector ℝ (N + 1)) (n r : ℕ)
    (hr : r ≤ n) (hn : n ≤ N) : Run ℝ := do
  let top ← StoredGivens.read F ⟨n, by omega⟩
  let first ← StoredGivens.read F ⟨r, by omega⟩
  let second ← StoredGivens.read F ⟨n - r, by omega⟩
  let denominator ← StoredGivens.mul first second
  StoredGivens.div top denominator

theorem chooseFrom_value {N : ℕ} (F : Vector ℝ (N + 1))
    (correct : ∀ i : Fin (N + 1), F[i.val] = (i.val.factorial : ℝ))
    (n r : ℕ) (hr : r ≤ n) (hn : n ≤ N) :
    (chooseFrom F n r hr hn).value = (n.choose r : ℝ) := by
  simp only [chooseFrom, bind, Run.bind, StoredGivens.read, StoredGivens.mul,
    StoredGivens.div, charge]
  rw [correct ⟨n, by omega⟩, correct ⟨r, by omega⟩, correct ⟨n-r, by omega⟩]
  exact (Nat.cast_choose ℝ hr).symm

noncomputable def sourceEntry (k : ℕ) (F : Vector ℝ (2 * k + 2)) (i : Fin (k + 1)) : Run ℝ :=
  sumEntries fun m : Fin (i.val + 1) => do
    let binomial ← chooseFrom F (k + i.val - m.val) k (by omega) (by omega)
    let denominator ← StoredGivens.read F ⟨m.val, by omega⟩
    StoredGivens.div binomial denominator

theorem sourceEntry_value (k : ℕ) (F : Vector ℝ (2 * k + 2))
    (correct : ∀ i : Fin (2 * k + 2), F[i.val] = (i.val.factorial : ℝ)) (i : Fin (k + 1)) :
    (sourceEntry k F i).value = sourceCoefficient k i.val := by
  rw [sourceEntry, sumEntries_value, sourceCoefficient_eq]
  simp only [bind, Run.bind, StoredGivens.read, StoredGivens.div, charge,
    chooseFrom_value F correct]
  rw [← Fin.sum_univ_eq_sum_range]
  apply Finset.sum_congr rfl
  intro m _
  rw [correct ⟨m.val, by omega⟩]

noncomputable def sources (k : ℕ) (F : Vector ℝ (2 * k + 2)) : Run (Vector ℝ (k + 1)) :=
  collect (sourceEntry k F)

theorem sources_value (k : ℕ) (F : Vector ℝ (2 * k + 2))
    (correct : ∀ i : Fin (2 * k + 2), F[i.val] = (i.val.factorial : ℝ)) (i : Fin (k + 1)) :
    (sources k F).value[i.val] = sourceCoefficient k i.val := by
  rw [sources, collect_value, sourceEntry_value k F correct]

noncomputable def leftTerm (k : ℕ) (F : Vector ℝ (2 * k + 2))
    (a : Vector ℝ (k + 1)) (denominator : ℝ) (r : Fin (2 * k + 2))
    (i : Fin (k + 1)) : Run ℝ :=
  let term : Run ℝ := if h : i.val ≤ r.val ∧ r.val ≤ k then do
    let coefficient ← StoredGivens.read a i
    let binomial ← chooseFrom F (k - i.val) (r.val - i.val) (by omega) (by omega)
    let numerator ← StoredGivens.mul coefficient binomial
    StoredGivens.div numerator denominator
  else pure 0
  ⟨term.value, 2 • tick .compare + term.cost⟩

noncomputable def leftEntry (k : ℕ) (F : Vector ℝ (2 * k + 2))
    (a : Vector ℝ (k + 1)) (r : Fin (2 * k + 2)) : Run ℝ := do
  let denominator ← chooseFrom F (2 * k + 1) r.val (by omega) (by omega)
  sumEntries (leftTerm k F a denominator r)

theorem leftEntry_value (k : ℕ) (F : Vector ℝ (2 * k + 2))
    (hF : ∀ i : Fin (2 * k + 2), F[i.val] = (i.val.factorial : ℝ))
    (a : Vector ℝ (k + 1)) (ha : ∀ i : Fin (k + 1), a[i.val] = sourceCoefficient k i.val)
    (r : Fin (2 * k + 2)) : (leftEntry k F a r).value = leftCoefficient k r.val := by
  simp only [leftEntry, bind, Run.bind, sumEntries_value, chooseFrom_value F hF]
  rw [leftCoefficient_eq, ← Fin.sum_univ_eq_sum_range]
  apply Finset.sum_congr rfl
  intro i _
  unfold leftTerm
  split_ifs with h
  · simp only [bind, Run.bind, StoredGivens.read, StoredGivens.mul,
      StoredGivens.div, charge, ha, chooseFrom_value F hF]
  · rfl

noncomputable def lefts (k : ℕ) (F : Vector ℝ (2 * k + 2)) (a : Vector ℝ (k + 1)) :
    Run (Vector ℝ (2 * k + 2)) := collect (leftEntry k F a)

theorem lefts_value (k : ℕ) (F : Vector ℝ (2 * k + 2))
    (hF : ∀ i : Fin (2 * k + 2), F[i.val] = (i.val.factorial : ℝ))
    (a : Vector ℝ (k + 1)) (ha : ∀ i : Fin (k + 1), a[i.val] = sourceCoefficient k i.val)
    (r : Fin (2 * k + 2)) : (lefts k F a).value[r.val] = leftCoefficient k r.val := by
  rw [lefts, collect_value, leftEntry_value k F hF a ha]

/-- All shared intermediate arrays are materialized before they are consumed. -/
noncomputable def fromConstant (k : ℕ) (e : ℝ) : Run (Vector ℝ (2 * k + 2)) := do
  let F ← factorials (2 * k + 1)
  let a ← sources k F.values
  let left ← lefts k F.values a
  collect fun r => do
    let x ← StoredGivens.read left r
    let y ← StoredGivens.read left ⟨2 * k + 1 - r.val, by omega⟩
    let scaled ← StoredGivens.mul e x
    StoredGivens.add scaled y

theorem fromConstant_value (k : ℕ) (e : ℝ) (r : Fin (2 * k + 2)) :
    (fromConstant k e).value[r.val] = e * leftCoefficient k r.val +
      leftCoefficient k (2 * k + 1 - r.val) := by
  simp only [fromConstant, bind, Run.bind, collect_value, StoredGivens.read,
    StoredGivens.mul, StoredGivens.add, charge]
  rw [lefts_value k _ (factorials_value _) _ (sources_value k _ (factorials_value _)) r,
    lefts_value k _ (factorials_value _) _ (sources_value k _ (factorials_value _))
      ⟨2 * k + 1 - r.val, by omega⟩]

/-- Extra source primitive accounting, deliberately separate from `Op`. -/
structure SourceRun (α : Type) where
  run : Run α
  exponentialCalls : ℕ

noncomputable def exponential (x : ℝ) : SourceRun ℝ := ⟨⟨Real.exp x, 0⟩, 1⟩

noncomputable def compile (k : ℕ) : SourceRun (Vector ℝ (2 * k + 2)) :=
  let e := exponential (-1)
  let result := fromConstant k e.run.value
  ⟨⟨result.value, e.run.cost + result.cost⟩, e.exponentialCalls⟩

theorem compile_value (k : ℕ) (r : Fin (2 * k + 2)) :
    (compile k).run.value[r.val] = sourceBernsteinCoefficient k r.val :=
  fromConstant_value k (Real.exp (-1)) r

theorem compile_nonneg (k : ℕ) (r : Fin (2 * k + 2)) :
    0 ≤ (compile k).run.value[r.val] := by
  rw [compile_value]
  exact sourceBernsteinCoefficient_nonneg _ _

theorem leftCoefficient_pos (k r : ℕ) (hr : r ≤ k) : 0 < leftCoefficient k r := by
  rw [leftCoefficient_eq]
  apply Finset.sum_pos'
  · intro i _
    split_ifs
    · exact div_nonneg (mul_nonneg (sourceCoefficient_nonneg _ _) (Nat.cast_nonneg _))
        (Nat.cast_nonneg _)
    · exact le_rfl
  · refine ⟨0, by simp, ?_⟩
    have zero : sourceCoefficient k 0 = 1 := HermitePolynomial.coefficientSeries_coeff_zero k
    simp only [Nat.zero_le, hr, and_self, if_true, zero, Nat.sub_zero, one_mul]
    exact div_pos (by exact_mod_cast Nat.choose_pos hr)
      (by exact_mod_cast Nat.choose_pos (show r ≤ 2 * k + 1 by omega))

/-- Every returned source coefficient is strictly positive, including k=0. -/
theorem compile_pos (k : ℕ) (r : Fin (2 * k + 2)) :
    0 < (compile k).run.value[r.val] := by
  rw [compile_value, sourceBernsteinCoefficient]
  by_cases h : r.val ≤ k
  · exact add_pos_of_pos_of_nonneg (mul_pos (Real.exp_pos _) (leftCoefficient_pos k _ h))
      (leftCoefficient_nonneg _ _)
  · exact add_pos_of_nonneg_of_pos
      (mul_nonneg (Real.exp_pos _).le (leftCoefficient_nonneg _ _))
      (leftCoefficient_pos k _ (by omega))

theorem compile_exponentialCalls (k : ℕ) : (compile k).exponentialCalls = 1 := rfl

private theorem tick_le_one (a b : Op) : tick a b ≤ 1 := by
  unfold tick
  split <;> omega

private theorem collect_cost_le {n : ℕ} (f : Fin n → Run α) (op : Op) (B : ℕ)
    (bound : ∀ i, (f i).cost op ≤ B) : (collect f).cost op ≤ n * (B + 4) := by
  rw [collect_cost]
  have hs : (∑ i : Fin n, (f i).cost op) ≤ n * B := by
    calc
      _ ≤ ∑ _i : Fin n, B := Finset.sum_le_sum (fun i _ => bound i)
      _ = _ := by simp
  have hr := tick_le_one .read op
  have hw := tick_le_one .write op
  nlinarith

theorem extend_cost_le {n : ℕ} (xs : Vector ℝ (n + 1)) (last : ℝ) (op : Op) :
    (extend xs last).cost op ≤ 6 * (n + 2) := by
  unfold extend
  have bound := collect_cost_le (fun i : Fin (n + 2) =>
    let result := if h : i.val < n + 1 then StoredGivens.read xs ⟨i.val, h⟩ else pure last
    ⟨result.value, tick .compare + result.cost⟩) op 2 (by
      intro i
      have hc := tick_le_one .compare op
      have hr := tick_le_one .read op
      by_cases h : i.val < n + 1 <;>
        simp [h, StoredGivens.read, charge, pure, Run.pure,
          Pi.add_apply] <;> omega)
  simpa [Nat.mul_comm] using bound

theorem factorials_cost_le (n : ℕ) (op : Op) :
    (factorials n).cost op ≤ 10 * (n + 1) ^ 2 := by
  induction n with
  | zero =>
      have hr := tick_le_one .read op
      have hw := tick_le_one .write op
      simp [factorials, bind, pure, Run.bind, Run.pure, collect_cost]
      omega
  | succ n ih =>
      have extension := extend_cost_le (factorials n).value.values
        ((factorials n).value.next * (factorials n).value.values[n]) op
      have hr := tick_le_one .read op
      have hf := tick_le_one .field op
      simp only [factorials, bind, pure, Run.bind, Run.pure, StoredGivens.read,
        StoredGivens.mul, StoredGivens.add, charge, Pi.add_apply, add_zero]
      nlinarith

theorem chooseFrom_cost {N : ℕ} (F : Vector ℝ (N + 1)) (n r : ℕ)
    (hr : r ≤ n) (hn : n ≤ N) (op : Op) :
    (chooseFrom F n r hr hn).cost op = 3 * tick .read op + 2 * tick .field op := by
  simp [chooseFrom, bind, Run.bind, StoredGivens.read, StoredGivens.mul,
    StoredGivens.div, charge]
  omega

theorem sourceEntry_cost_le (k : ℕ) (F : Vector ℝ (2 * k + 2))
    (i : Fin (k + 1)) (op : Op) : (sourceEntry k F i).cost op ≤ 8 * (k + 1) := by
  have hr := tick_le_one .read op
  have hf := tick_le_one .field op
  unfold sourceEntry
  have bound := sumEntries_cost_le (fun m : Fin (i.val + 1) => do
    let binomial ← chooseFrom F (k + i.val - m.val) k (by omega) (by omega)
    let denominator ← StoredGivens.read F ⟨m.val, by omega⟩
    StoredGivens.div binomial denominator) op 7 (by
      intro m
      simp only [bind, Run.bind, StoredGivens.read, StoredGivens.div, charge,
        Pi.add_apply, chooseFrom_cost]
      omega)
  have hi := i.isLt
  nlinarith

theorem sources_cost_le (k : ℕ) (F : Vector ℝ (2 * k + 2)) (op : Op) :
    (sources k F).cost op ≤ 12 * (k + 1) ^ 2 := by
  have bound := collect_cost_le (sourceEntry k F) op (8 * (k + 1))
    (fun i => sourceEntry_cost_le k F i op)
  change (collect (sourceEntry k F)).cost op ≤ _
  nlinarith

theorem leftTerm_cost_le (k : ℕ) (F : Vector ℝ (2 * k + 2))
    (a : Vector ℝ (k + 1)) (denominator : ℝ) (r : Fin (2 * k + 2))
    (i : Fin (k + 1)) (op : Op) : (leftTerm k F a denominator r i).cost op ≤ 10 := by
  have hr := tick_le_one .read op
  have hf := tick_le_one .field op
  have hc := tick_le_one .compare op
  unfold leftTerm
  by_cases h : i.val ≤ r.val ∧ r.val ≤ k <;>
    simp [h, bind, pure, Run.bind, Run.pure,
      StoredGivens.read, StoredGivens.mul, StoredGivens.div, charge,
      Pi.add_apply, chooseFrom_cost] <;> omega

theorem leftEntry_cost_le (k : ℕ) (F : Vector ℝ (2 * k + 2))
    (a : Vector ℝ (k + 1)) (r : Fin (2 * k + 2)) (op : Op) :
    (leftEntry k F a r).cost op ≤ 16 * (k + 1) := by
  have hr := tick_le_one .read op
  have hf := tick_le_one .field op
  let denominator := (chooseFrom F (2 * k + 1) r.val (by omega) (by omega)).value
  have bound := sumEntries_cost_le (leftTerm k F a denominator r) op 10
    (fun i => leftTerm_cost_le k F a denominator r i op)
  dsimp only [denominator] at bound
  simp only [leftEntry, bind, Run.bind, Pi.add_apply, chooseFrom_cost]
  change 3 * tick .read op + 2 * tick .field op + _ ≤ _
  change (sumEntries _).cost op ≤ _ at bound
  nlinarith

theorem lefts_cost_le (k : ℕ) (F : Vector ℝ (2 * k + 2))
    (a : Vector ℝ (k + 1)) (op : Op) : (lefts k F a).cost op ≤ 40 * (k + 1) ^ 2 := by
  have bound := collect_cost_le (leftEntry k F a) op (16 * (k + 1))
    (fun r => leftEntry_cost_le k F a r op)
  change (collect (leftEntry k F a)).cost op ≤ _
  nlinarith

/-- Quadratic bound for every ordinary operation category of the same run. -/
theorem fromConstant_cost_le (k : ℕ) (e : ℝ) (op : Op) :
    (fromConstant k e).cost op ≤ 108 * (k + 1) ^ 2 := by
  have fact := factorials_cost_le (2 * k + 1) op
  have src := sources_cost_le k (factorials (2 * k + 1)).value.values op
  have left := lefts_cost_le k (factorials (2 * k + 1)).value.values
    (sources k (factorials (2 * k + 1)).value.values).value op
  let values := (lefts k (factorials (2 * k + 1)).value.values
    (sources k (factorials (2 * k + 1)).value.values).value).value
  have final := collect_cost_le (fun r : Fin (2 * k + 2) => do
    let x ← StoredGivens.read values r
    let y ← StoredGivens.read values ⟨2 * k + 1 - r.val, by omega⟩
    let scaled ← StoredGivens.mul e x
    StoredGivens.add scaled y) op 4 (by
      intro r
      have hr := tick_le_one .read op
      have hf := tick_le_one .field op
      simp only [bind, Run.bind, StoredGivens.read, StoredGivens.mul,
        StoredGivens.add, charge, Pi.add_apply]
      omega)
  dsimp only [values] at final
  simp only [bind, Run.bind] at final
  simp only [fromConstant, bind, Run.bind, Pi.add_apply]
  nlinarith

theorem compile_cost_le (k : ℕ) (op : Op) :
    (compile k).run.cost op ≤ 108 * (k + 1) ^ 2 := by
  simpa only [compile, exponential, Pi.add_apply, Pi.zero_apply, zero_add] using
    fromConstant_cost_le k (Real.exp (-1)) op

/-- The separate exponential count is exactly one and is not in this sum. -/
theorem compile_total_cost_le (k : ℕ) :
    StoredRectangularGivens.total (compile k).run.cost ≤ 864 * (k + 1) ^ 2 := by
  have h1 := compile_cost_le k .field
  have h2 := compile_cost_le k .sqrt
  have h3 := compile_cost_le k .angle
  have h4 := compile_cost_le k .trig
  have h5 := compile_cost_le k .compare
  have h6 := compile_cost_le k .read
  have h7 := compile_cost_le k .write
  have h8 := compile_cost_le k .emit
  simp only [StoredRectangularGivens.total]
  omega

end QuantumBlockEncoding.StoredHermiteCoefficients
