import QuantumBlockEncoding.BasisIncrementAllXConjugation
import QuantumBlockEncoding.BinaryCarryTelescoping
import QuantumBlockEncoding.ComparatorIncrementerEq39BasisCascade
import QuantumBlockEncoding.ComparatorIncrementerEq39BlockCascade
import QuantumBlockEncoding.ComparatorIncrementerEq39LocalActivation
import QuantumBlockEncoding.ComparatorIncrementerEq39SquareRootPlan
import QuantumBlockEncoding.ComparatorIncrementerLemma8BlockCascadeCertificate
import QuantumBlockEncoding.ComparatorIncrementerLemma8Lemma7LocalBounds
import QuantumBlockEncoding.ComparatorIncrementerLemma8PromiseDepthBudget
import QuantumBlockEncoding.ComparatorIncrementerLemma8PromiseGateBudget
import QuantumBlockEncoding.ComparatorIncrementerLemma8ResourceClosureFromLemma7
import QuantumBlockEncoding.ComparatorIncrementerTheorem4OptimalityContract
import QuantumBlockEncoding.GidneyZeroedControlledStrongPromise
import QuantumBlockEncoding.GidneyZeroedEq35Promise
import QuantumBlockEncoding.GidneyZeroedLemma7BasisWitness
import QuantumBlockEncoding.GidneyZeroedPrimitive
import QuantumBlockEncoding.GidneyZeroedScheduledFamily
import QuantumBlockEncoding.GidneyZeroedSourceDecrement
import QuantumBlockEncoding.GidneyZeroedSourceLogicalResources
import QuantumBlockEncoding.GidneyZeroedSourceStrongPromise
import QuantumBlockEncoding.MixedRadixIncrement
import QuantumBlockEncoding.StrongPromiseInverse

/-!
# Vandaele incrementer formalization spine

Thin aggregation module for the current source-facing incrementer proof graph.
It deliberately contains no new theorem: arithmetic, promise semantics, actual
Gidney gate proofs, Equation-(39) block semantics, Lemma-8 resource closure, and
Theorem-4 conditional optimality remain independent Lean nodes.
-/
