import QuantumBlockEncoding.PrimitiveBasisRegisterSplit
import QuantumBlockEncoding.VandaeleClassicalAdderTarget
import QuantumBlockEncoding.VandaeleTheorem5AdderCarry
import Mathlib.Tactic

/-!
# Basis-register bridge for Vandaele Figure 11

The arithmetic carry theorem works with natural low/high digits.  Figure 11 acts
on actual computational-basis subregisters.  This module gives the exact bridge.

For an n-bit basis state, split it into

`ceil(n/2)` low bits and `floor(n/2)` high bits.

The low block adds cL; the high block adds cH plus the carry generated by the
original low block.  Recombining those two basis outputs is exactly the canonical
n-bit modular adder by c.

This is a semantic Figure-11 theorem, not yet the recursive low-resource circuit.
-/

namespace QuantumBlockEncoding
namespace VandaeleTheorem5AdderBasisSplit

open ComparatorIncrementerGeneral
open PrimitiveBasisRegisterSplit
open VandaeleClassicalAdderTarget
open VandaeleTheorem5AdderCarry
open ZModPrimitiveBasisBridge

/-- Equality transport for dependent primitive-basis widths. -/
def basisWidthEquiv {a b : Nat} (equal : a = b) :
    PrimitiveBasis a ≃ PrimitiveBasis b := by
  subst b
  exact Equiv.refl _

/-- Canonical Figure-11 target-register split. -/
def adderSplitEquiv (n : Nat) :
    PrimitiveBasis n ≃
      PrimitiveBasis (lowWidth n) × PrimitiveBasis (highWidth n) :=
  (basisWidthEquiv (low_add_high n).symm).trans
    (basisSplitEquiv (lowWidth n) (highWidth n))

/-- Numerical low digit of the split basis state. -/
def lowDigit (n : Nat) (state : PrimitiveBasis n) : Nat :=
  basisNat (lowWidth n) (adderSplitEquiv n state).1

/-- Numerical high digit. -/
def highDigit (n : Nat) (state : PrimitiveBasis n) : Nat :=
  basisNat (highWidth n) (adderSplitEquiv n state).2

/-- Split basis value recomposes exactly. -/
theorem basisNat_recompose
    (n : Nat) (state : PrimitiveBasis n) :
    basisNat n state = lowDigit n state + lowBase n * highDigit n state := by
  unfold basisNat lowDigit highDigit adderSplitEquiv
  let widened := basisWidthEquiv (low_add_high n).symm state
  have value := primitiveBasisLEEquiv_combineBasis_value
    (lowWidth n) (highWidth n)
    (basisSplitEquiv (lowWidth n) (highWidth n) widened)
  have reconstructed := (basisSplitEquiv (lowWidth n) (highWidth n)).symm_apply_apply widened
  rw [basisSplitEquiv_symm_apply] at reconstructed
  rw [reconstructed] at value
  simpa [lowBase, gridSize, widened, basisWidthEquiv] using value

/-- Low digit is the natural-number low part from the arithmetic theorem. -/
theorem lowDigit_eq_lowPart
    (n : Nat) (state : PrimitiveBasis n) :
    lowDigit n state = lowPart n (basisNat n state) := by
  have rec := basisNat_recompose n state
  unfold lowPart
  rw [rec]
  have lowBound : lowDigit n state < lowBase n := by
    unfold lowDigit basisNat lowBase
    exact (primitiveBasisLEEquiv (lowWidth n) (adderSplitEquiv n state).1).isLt
  rw [Nat.add_mul_mod_self_left]
  exact Nat.mod_eq_of_lt lowBound

/-- High digit is the corresponding quotient. -/
theorem highDigit_eq_highPart
    (n : Nat) (state : PrimitiveBasis n) :
    highDigit n state = highPart n (basisNat n state) := by
  have rec := basisNat_recompose n state
  unfold highPart
  rw [rec]
  have basePositive : 0 < lowBase n := by
    unfold lowBase gridSize
    exact Nat.pow_pos (by decide)
  have highBound : highDigit n state < highBase n := by
    unfold highDigit basisNat highBase
    exact (primitiveBasisLEEquiv (highWidth n) (adderSplitEquiv n state).2).isLt
  rw [Nat.add_mul_div_left _ _ basePositive]
  have lowBound : lowDigit n state < lowBase n := by
    unfold lowDigit basisNat lowBase
    exact (primitiveBasisLEEquiv (lowWidth n) (adderSplitEquiv n state).1).isLt
  rw [Nat.div_eq_of_lt lowBound, Nat.zero_add, Nat.mod_eq_of_lt highBound]

/-- Figure-11 semantic output pair. -/
def splitAdderOutput
    (n : Nat) (constant : Fin (gridSize n))
    (state : PrimitiveBasis n) :
    PrimitiveBasis (lowWidth n) × PrimitiveBasis (highWidth n) :=
  let split := adderSplitEquiv n state
  let carry := carryBit n (basisNat n state) constant.val
  (basisModularAddEquiv (lowWidth n)
      (natConstant (lowWidth n) (lowPart n constant.val)) split.1,
   basisModularAddEquiv (highWidth n)
      (natConstant (highWidth n) (highPart n constant.val + carry)) split.2)

/-- Recombine the Figure-11 pair to one n-bit output register. -/
def splitAdderEquivAction
    (n : Nat) (constant : Fin (gridSize n))
    (state : PrimitiveBasis n) : PrimitiveBasis n :=
  (adderSplitEquiv n).symm (splitAdderOutput n constant state)

/-- Low output digit agrees with the arithmetic low output. -/
theorem splitAdderOutput_low_value
    (n : Nat) (constant : Fin (gridSize n))
    (state : PrimitiveBasis n) :
    basisNat (lowWidth n) (splitAdderOutput n constant state).1 =
      lowOutput n (basisNat n state) constant.val := by
  unfold splitAdderOutput lowOutput
  rw [basisModularAdd_nat_value]
  rw [lowDigit_eq_lowPart]
  rfl

/-- High output digit agrees with the arithmetic high output. -/
theorem splitAdderOutput_high_value
    (n : Nat) (constant : Fin (gridSize n))
    (state : PrimitiveBasis n) :
    basisNat (highWidth n) (splitAdderOutput n constant state).2 =
      highOutput n (basisNat n state) constant.val := by
  unfold splitAdderOutput highOutput
  rw [basisModularAdd_nat_value]
  rw [highDigit_eq_highPart]
  rfl

/-- Numerical action of the recombined Figure-11 semantic split. -/
theorem splitAdderAction_value
    (n : Nat) (constant : Fin (gridSize n))
    (state : PrimitiveBasis n) :
    basisNat n (splitAdderEquivAction n constant state) =
      (basisNat n state + constant.val) % gridSize n := by
  have xBound : basisNat n state < gridSize n := by
    unfold basisNat
    exact (primitiveBasisLEEquiv n state).isLt
  have arithmetic := add_recomposition
    n (basisNat n state) constant.val xBound constant.isLt
  unfold splitAdderEquivAction
  let output := splitAdderOutput n constant state
  have recomposed :
      basisNat n ((adderSplitEquiv n).symm output) =
        basisNat (lowWidth n) output.1 +
          lowBase n * basisNat (highWidth n) output.2 := by
    have applySplit := basisNat_recompose n ((adderSplitEquiv n).symm output)
    have splitBack :
        adderSplitEquiv n ((adderSplitEquiv n).symm output) = output :=
      (adderSplitEquiv n).apply_symm_apply output
    simpa [lowDigit, highDigit, splitBack] using applySplit
  rw [recomposed]
  rw [splitAdderOutput_low_value, splitAdderOutput_high_value]
  exact arithmetic

/-- Exact equality with the canonical basis adder. -/
theorem splitAdderAction_eq_canonical
    (n : Nat) (constant : Fin (gridSize n)) :
    splitAdderEquivAction n constant =
      basisModularAddEquiv n (natConstant n constant.val) := by
  funext state
  apply (primitiveBasisLEEquiv n).injective
  apply Fin.ext
  have left := splitAdderAction_value n constant state
  have right := basisModularAdd_nat_value n constant.val state
  unfold basisNat at left right
  exact left.trans right.symm

end VandaeleTheorem5AdderBasisSplit
end QuantumBlockEncoding
