"""Curated QuantumComputinglib teaching content for ASPBE.

Declaration names in this file are validated against the generated inventory by
``website/scripts/build_site.py``.  The prose may explain a broader route, but it
must never upgrade that route beyond the status carried here.
"""

from __future__ import annotations


STATUS_ORDER = (
    "Compiled",
    "Partial route",
    "Stated, proof incomplete",
    "Experimental",
    "Planned",
    "Blocked",
)


def result(
    declaration: str,
    title: str,
    plain: str,
    math: str,
    intuition: str,
    why: str,
    dependencies: list[str],
    proof_idea: str,
    correspondence: list[tuple[str, str]],
    local_status: str,
    route_status: str,
    missing: str = "None for this local declaration.",
    route_closures: list[str] | None = None,
) -> dict[str, object]:
    return {
        "declaration": declaration,
        "title": title,
        "plain": plain,
        "math": math,
        "intuition": intuition,
        "why": why,
        "dependencies": dependencies,
        "proof_idea": proof_idea,
        "correspondence": correspondence,
        "local_status": local_status,
        "route_status": route_status,
        "missing": missing,
        "route_closures": route_closures or
            ([declaration] if route_status == "Compiled" else []),
    }


CHAPTERS = [
    {
        "slug": "linear-algebra",
        "number": 1,
        "track": "Shared foundations",
        "title": "Vectors, matrices, and basis states",
        "summary": (
            "Fix the finite matrix model, pointwise equality, dimensions, and "
            "resource records used by every later certificate."
        ),
        "modules": [
            "QuantumBlockEncoding/Core.lean",
            "QuantumBlockEncoding/Resources.lean",
        ],
        "diagram": "module-dependencies",
        "results": [
            result(
                "QuantumBlockEncoding.Matrix.PointwiseEq",
                "Pointwise matrix equality",
                "Two finite matrices are equal when every indexed entry agrees.",
                r"A = B \;\Longleftrightarrow\; \forall i\,j,\; A_{ij}=B_{ij}.",
                "Matrix goals become explicit finite entry goals that Lean can rewrite.",
                "Block extraction and candidate validation are ultimately entrywise claims.",
                ["QuantumBlockEncoding.Matrix"],
                "Expose row and column indices, prove the scalar equality, then recover matrix equality.",
                [
                    ("Choose arbitrary indices.", "intro i j"),
                    ("Reduce the matrix claim to the selected entry.", "apply Matrix.ext"),
                ],
                "Compiled",
                "Compiled",
            ),
            result(
                "QuantumBlockEncoding.Resource",
                "Executable resource records",
                "A candidate carries named resource counts instead of an informal cost label.",
                r"r=(q_{\mathrm{anc}},q_{\mathrm{tot}},d,n_{1q},n_{2q}).",
                "The proof object and the engineering cost can be compared without conflating them.",
                "Candidate search needs deterministic, auditable scoring fields.",
                ["QuantumBlockEncoding.gridSize"],
                "Represent each resource coordinate as data and derive decidable comparison support.",
                [
                    ("Store each cost coordinate.", "structure Resource"),
                    ("Expose values to scoring and export code.", "deriving Repr"),
                ],
                "Compiled",
                "Compiled",
                "None within the declared reusable route.",
                route_closures=[
                    "QuantumBlockEncoding.ExecutableResourceCertificate.resource_eq_program_resource",
                    "QuantumBlockEncoding.ExecutableResourceCertificate.cost_gateCount",
                    "QuantumBlockEncoding.ExecutableResourceCertificate.cost_depth",
                ],
            ),
        ],
    },
    {
        "slug": "state-preparation",
        "number": 3,
        "track": "State preparation",
        "title": "The state-preparation problem",
        "summary": (
            "Ask one concrete question: which unitary sends the all-zero basis "
            "state to the normalized state we want?"
        ),
        "modules": [
            "QuantumBlockEncoding/StatePreparation.lean",
            "QuantumBlockEncoding/ConcreteSemantics.lean",
            "QuantumBlockEncoding/TextbookStatePreparation.lean",
        ],
        "diagram": "state-preparation-flow",
        "results": [
            result(
                "QuantumBlockEncoding.TextbookStatePreparation.hadamardCertificate_prepares_plus",
                "Hadamard prepares the plus state",
                "The standard Hadamard matrix is proved unitary and maps the zero ket to the normalized equal superposition.",
                r"H|0\rangle=(|0\rangle+|1\rangle)/\sqrt{2}.",
                "The first column of H contains the two target amplitudes, both equal to one over square root two.",
                "This is the smallest complete example where normalization is genuinely more than a basis-vector check.",
                [
                    "QuantumBlockEncoding.TextbookStatePreparation.hadamard_unitary",
                    "QuantumBlockEncoding.TextbookStatePreparation.plusTarget_normalized",
                ],
                "Prove the square-root identity, check H times its conjugate transpose is identity, and identify column zero with the target vector.",
                [
                    ("Prove the target has norm one.", "plusTarget_normalized"),
                    ("Prove the matrix is unitary.", "hadamard_unitary"),
                    ("Evaluate H on the zero ket.", "hadamard_prepares_plus"),
                    ("Package all three facts.", "hadamardCertificate"),
                ],
                "Compiled",
                "Compiled",
            ),
            result(
                "QuantumBlockEncoding.TextbookStatePreparation.pauliXCertificate_prepares_one",
                "Pauli X prepares the one state",
                "The Pauli X permutation is proved unitary and sends the zero basis state to the one basis state.",
                r"X|0\rangle=|1\rangle,\qquad X|1\rangle=|0\rangle.",
                "X swaps the two basis columns; selecting its first column therefore gives the one-state amplitudes.",
                "It gives beginners a complete certificate without irrational amplitudes or hidden analytic assumptions.",
                [
                    "QuantumBlockEncoding.TextbookStatePreparation.pauliX_unitary",
                    "QuantumBlockEncoding.TextbookStatePreparation.oneTarget_normalized",
                ],
                "Use Mathlib's swap matrix, its self-inverse theorem, and the basis-ket column-selection lemma.",
                [
                    ("Represent X as a swap matrix.", "pauliX"),
                    ("Use self-inverse to prove unitarity.", "pauliX_unitary"),
                    ("Select the zero-input column.", "pauliX_prepares_one"),
                    ("Package the certificate and cost.", "pauliXVerified"),
                ],
                "Compiled",
                "Compiled",
            ),
            result(
                "QuantumBlockEncoding.StatePreparationCandidate.preparesTarget",
                "The state-preparation contract",
                "The candidate unitary prepares the target from the zero basis state.",
                r"U\lvert 0^n\rangle=\lvert\psi\rangle.",
                "The target amplitudes are the first column of the unitary matrix.",
                "It gives state preparation its own acceptance test, independent of any later use in block encoding.",
                [
                    "QuantumBlockEncoding.StatePreparationTarget",
                    "QuantumBlockEncoding.StatePreparationCandidate",
                ],
                "Unfold the candidate action on the zero basis vector and compare every amplitude.",
                [
                    ("Select the all-zero input column.", "candidate.unitary row (zeroBasisIndex qubits)"),
                    ("Match it with the requested amplitude.", "= candidate.target.amplitudes row"),
                ],
                "Compiled",
                "Compiled",
                "None within the declared reusable route.",
                route_closures=[
                    "QuantumBlockEncoding.StatePreparationCandidate.certify",
                    "QuantumBlockEncoding.StatePreparationCandidate.certify_firstColumn",
                ],
            ),
        ],
    },
    {
        "slug": "state-preparation-certificates",
        "number": 4,
        "track": "State preparation",
        "title": "Reading and reusing a preparation certificate",
        "summary": (
            "Connect the ket equation to a matrix column, package the proof, "
            "and reuse exact preparation where an approximate interface is expected."
        ),
        "modules": [
            "QuantumBlockEncoding/StatePreparation.lean",
            "QuantumBlockEncoding/ConcreteSemantics.lean",
            "QuantumBlockEncoding/TextbookStatePreparation.lean",
        ],
        "diagram": "state-preparation-flow",
        "results": [
            result(
                "QuantumBlockEncoding.ConcreteSemantics.firstColumnMatches_iff_applyVec_zeroKet",
                "The ket equation is a first-column statement",
                "Matrix action on the all-zero ket selects exactly the first column of the unitary.",
                r"\operatorname{column}_0(U)=\psi\iff U\lvert0^n\rangle=\lvert\psi\rangle.",
                "There are two common ways to say the same fact: physicists write a ket equation, while the finite Lean model compares indexed amplitudes.",
                "This bridge keeps proofs and circuit explanations in the same convention.",
                [
                    "QuantumBlockEncoding.FirstColumnMatches",
                    "QuantumBlockEncoding.ConcreteSemantics.applyVec_zeroKet",
                ],
                "Acting on a basis vector selects one matrix column; function extensionality then turns vector equality into entrywise equality.",
                [
                    ("Apply the matrix to the zero basis ket.", "applyVec_zeroKet"),
                    ("Compare every output amplitude.", "funext / congrFun"),
                ],
                "Compiled",
                "Compiled",
                "None within the declared reusable route.",
                route_closures=[
                    "QuantumBlockEncoding.ConcreteSemantics.ComplexStatePreparationCertificate.ofFirstColumn",
                    "QuantumBlockEncoding.ConcreteSemantics.ComplexStatePreparationCertificate.verifiedOfFirstColumn",
                    "QuantumBlockEncoding.ConcreteSemantics.ComplexStatePreparationCertificate.verifiedOfFirstColumn_preparesTarget",
                ],
            ),
            result(
                "QuantumBlockEncoding.VerifiedStatePreparation.firstColumn",
                "A verified preparer exposes its amplitudes",
                "Once the certificate is built, downstream proofs can read its first-column identity directly.",
                r"U_{i,0}=\psi_i.",
                "The certificate hides the packaging work but does not weaken the statement.",
                "Prepared amplitudes are often the input to later LCU or oracle constructions.",
                ["QuantumBlockEncoding.VerifiedStatePreparation"],
                "Project the stored preparation proof from the verified record.",
                [
                    ("Read the certified state-action field.", "verified.preparationProof"),
                    ("Expose it through the public theorem.", "verified.firstColumn"),
                ],
                "Compiled",
                "Compiled",
            ),
            result(
                "QuantumBlockEncoding.VerifiedStatePreparation.asZeroErrorApprox",
                "Exact preparation can enter an approximate interface",
                "An exact certificate is also an approximate certificate with error zero.",
                r"\varepsilon=0.",
                "The tolerance ladder can reuse exact work instead of changing certificate formats.",
                "Exact and approximate searches need one stable consumer boundary.",
                ["QuantumBlockEncoding.VerifiedStatePreparation"],
                "Reuse normalization, unitarity, and preparation proofs while setting the approximation field to the exact predicate.",
                [
                    ("Keep the same candidate and proofs.", "verified.candidate / normalizationProof / unitaryProof"),
                    ("Set the error to zero.", "epsilon := 0"),
                ],
                "Compiled",
                "Compiled",
            ),
        ],
    },
    {
        "slug": "circuit-semantics",
        "number": 2,
        "track": "Shared foundations",
        "title": "Gates, unitaries, and circuit meaning",
        "summary": (
            "Separate gate syntax from matrix evaluation and make register order "
            "an explicit part of the semantic boundary."
        ),
        "modules": [
            "QuantumBlockEncoding/Circuit.lean",
            "QuantumBlockEncoding/CircuitSemantics.lean",
            "QuantumBlockEncoding/ConcreteSemantics.lean",
        ],
        "diagram": "certificate-pipeline",
        "results": [
            result(
                "QuantumBlockEncoding.evalGateMatrices",
                "Circuit matrix evaluation",
                "A list of gate matrices is folded into one matrix in the library's declared application order.",
                r"\llbracket[g_1,\ldots,g_m]\rrbracket=G_m\cdots G_1.",
                "The list is executable syntax; its fold is the matrix used by proofs.",
                "Without one order convention, circuit diagrams and matrix products can silently disagree.",
                ["QuantumBlockEncoding.GateMatrix", "QuantumBlockEncoding.Matrix"],
                "Recursively multiply the next gate matrix on the side fixed by the semantics.",
                [
                    ("Empty circuit is identity.", "evalGateMatrices []"),
                    ("Compose the next gate.", "evalGateMatrices (g :: gs)"),
                ],
                "Compiled",
                "Compiled",
            ),
            result(
                "QuantumBlockEncoding.ConcreteSemantics.signalSystemBlockProjection_eq_cleanBlockProduct",
                "Flat and product-register clean blocks agree",
                "The two ASPBE block-projection views are pointwise equal under the shared register order.",
                r"\Pi_s U\Pi_s^\dagger=\operatorname{cleanBlockProduct}(s,U).",
                "A circuit-semantics proof can be consumed by classic block-encoding arithmetic without index reconstruction.",
                "Register-shape mismatches were a repeated historical failure class.",
                [
                    "QuantumBlockEncoding.signalSystemBlockProjection",
                    "QuantumBlockEncoding.BlockEncodingClassics.cleanBlockProduct",
                ],
                "Both definitions use the same signal-major flattened index, so the pointwise proof is definitional.",
                [
                    ("Fix system row and column.", "intro row col"),
                    ("Unfold the shared index.", "rfl"),
                ],
                "Compiled",
                "Compiled",
                "None within the declared reusable route.",
                route_closures=[
                    "QuantumBlockEncoding.ConcreteSemantics.exactCleanBlockOfSignalProjection",
                    "QuantumBlockEncoding.ConcreteSemantics.exactCleanBlockOfSignalProjection_correct",
                ],
            ),
            result(
                "QuantumBlockEncoding.CircuitMatrixSemantics.blockExtractionTarget",
                "Circuit-to-block extraction target",
                "Circuit semantics selects the signal-system block that must match the scaled target operator.",
                r"(\langle0^a\rvert\otimes I)\,U\,(|0^a\rangle\otimes I)=A/\alpha.",
                "Ancillas are fixed to zero on both sides; the remaining indices are the signal system.",
                "It connects an executable gate list to the mathematical block-encoding contract.",
                [
                    "QuantumBlockEncoding.CircuitMatrixSemantics",
                    "QuantumBlockEncoding.signalSystemBlockProjection",
                ],
                "Evaluate the gate list, project the ancilla-zero rows and columns, then compare the signal entries.",
                [
                    ("Evaluate syntax.", "CircuitMatrixSemantics.ofGateMatrices"),
                    ("Extract the selected block.", "signalSystemBlockProjection"),
                ],
                "Compiled",
                "Compiled",
                "None within the declared reusable route.",
                route_closures=[
                    "QuantumBlockEncoding.CertifiedCircuitBlockExtraction.extractionTarget",
                    "QuantumBlockEncoding.CertifiedCircuitBlockExtraction.exactCleanBlock",
                    "QuantumBlockEncoding.CertifiedCircuitBlockExtraction.exactCleanBlock_correct",
                ],
            ),
            result(
                "QuantumBlockEncoding.ConcreteSemantics.pointwiseProjection_iff_cleanBasisAction",
                "Projected block and clean-branch action agree",
                "Checking every clean projected entry is equivalent to checking the clean output amplitude after acting on every clean basis input.",
                r"\Pi U\Pi^\dagger=B\iff \langle0^a,i|U|0^a,j\rangle=B_{ij}.",
                "This is the finite-matrix bridge between the projected-block definition and the action-on-a-state proof style used in circuit derivations.",
                "Readers can follow a paper's state evolution without changing the mathematical acceptance contract.",
                [
                    "QuantumBlockEncoding.ConcreteSemantics.cleanBasisActionAmplitude",
                    "QuantumBlockEncoding.ConcreteSemantics.applyVec_basisKet",
                ],
                "Apply the matrix to a basis ket, use column selection, and identify the clean signal-system row.",
                [
                    ("Select one clean basis input.", "applyVec_basisKet"),
                    ("Read one clean output amplitude.", "cleanBasisActionAmplitude_eq_signalSystemBlockProjection"),
                    ("Quantify over both system indices.", "pointwiseProjection_iff_cleanBasisAction"),
                ],
                "Compiled",
                "Compiled",
                "None within the finite basis-action/projection bridge.",
                route_closures=[
                    "QuantumBlockEncoding.ConcreteSemantics.cleanBasisActionAmplitude_eq_signalSystemBlockProjection",
                    "QuantumBlockEncoding.ConcreteSemantics.pointwiseProjection_iff_cleanBasisAction",
                ],
            ),
        ],
    },
    {
        "slug": "block-encoding",
        "number": 5,
        "track": "Block encoding",
        "title": "The block-encoding contract",
        "summary": (
            "State the block contract with normalization, explicit register "
            "layout, and a verifier-facing certificate record."
        ),
        "modules": ["QuantumBlockEncoding/BlockEncoding.lean"],
        "diagram": "block-encoding-flow",
        "results": [
            result(
                "QuantumBlockEncoding.OperatorBlockEncodingCandidate.cost",
                "Candidate cost is derived from its layout",
                "The block-encoding candidate exposes a deterministic cost tuple from its declared registers and circuit resources.",
                r"c(U)=(a,q,d,n_{1q},n_{2q},\ldots).",
                "A candidate is not accepted only because its matrix works; alternatives remain rankable.",
                "The search layer needs a stable objective before proof attempts consume more budget.",
                [
                    "QuantumBlockEncoding.OperatorBlockEncodingCandidate",
                    "QuantumBlockEncoding.RegisterLayout",
                    "QuantumBlockEncoding.BlockEncodingCost",
                ],
                "Read the layout and circuit fields and assemble the canonical cost record.",
                [
                    ("Read ancillary and signal sizes.", "candidate.layout"),
                    ("Build the score tuple.", "candidate.cost"),
                ],
                "Compiled",
                "Compiled",
                "None within the declared reusable route.",
                route_closures=[
                    "QuantumBlockEncoding.OperatorBlockEncodingCandidate.cost_eq_fromLayoutAndResource",
                    "QuantumBlockEncoding.OperatorBlockEncodingCandidate.certify",
                ],
            ),
            result(
                "QuantumBlockEncoding.VerifiedOperatorBlockEncoding.asZeroErrorApprox",
                "Exact certificates are zero-error approximate certificates",
                "Every exact verified block encoding can be reused where an approximation with epsilon zero is expected.",
                r"\left\|A-\alpha\Pi U\Pi^\dagger\right\|=0.",
                "Exactness is the strongest point on the tolerance ladder.",
                "The harness can begin exact and relax epsilon without changing the consumer interface.",
                [
                    "QuantumBlockEncoding.VerifiedOperatorBlockEncoding",
                    "QuantumBlockEncoding.QueryOperatorTarget",
                ],
                "Rewrite with the exact block identity; the residual is the zero matrix.",
                [
                    ("Use the stored exact equality.", "verified.correct"),
                    ("Package error zero.", "verified.asZeroErrorApprox"),
                ],
                "Compiled",
                "Compiled",
            ),
        ],
    },
    {
        "slug": "classic-routes",
        "number": 6,
        "track": "Block encoding",
        "title": "Construction routes and composition rules",
        "summary": (
            "Reuse permutation, one-sparse, LCU, product, dilation, and QSVT "
            "interfaces instead of rediscovering each route per benchmark."
        ),
        "modules": [
            "QuantumBlockEncoding/BlockEncodingClassics.lean",
            "QuantumBlockEncoding/BandedSparseAccess.lean",
            "QuantumBlockEncoding/BandedSparseAccessPrimitive.lean",
        ],
        "diagram": "module-dependencies",
        "results": [
result(
    "QuantumBlockEncoding.BandedSparseAccess.accessEquiv_clean_slot",
    "Banded sparse address access",
    "The arbitrary-size loader-plus-SUM semantics is unitary, and a clean three-bit instance is refined to the exact primitive basis.",
    r"|0^{n-l}\rangle|s\rangle|i\rangle\mapsto|r_{s0}+i\bmod 2^n\rangle|i\rangle.",
    "The source-dependent loader chooses the first-row offset; the reusable SUM operation shifts it to row i.",
    "The generic semantics matches the cited construction, while the finite primitive witness proves that the compiler boundary is executable and oracle-free.",
    [
        "QuantumBlockEncoding.BandedSparseAccess.modularSumEquiv",
        "QuantumBlockEncoding.BandedSparseAccess.accessMatrix_unitary",
        "QuantumBlockEncoding.BandedSparseAccess.primitiveAccess3Program_eval",
    ],
    "Compose the generic finite equivalences, then instantiate an XOR-three loader, compile its modular adder to X/RY/RZ/CX, and prove clean action, unitarity, and zero unresolved oracle calls.",
    [
        ("Load the first-row band offset.", "liftLoaderEquiv / primitiveOffset3"),
        ("Add the preserved row modulo 2^n.", "modularSumEquiv / modularAdd3ReversibleProgram"),
        ("Prove the clean selected address.", "accessEquiv_clean_slot / primitiveAccess3_cleanAction"),
        ("Refine the finite witness to primitive matrices.", "primitiveAccess3Program_eval"),
    ],
    "Compiled",
    "Compiled",
    "None within the declared semantic-plus-finite-compiler route. The paper's arbitrary-size one-qubit/CNOT upper bound remains a separate general compiler theorem.",
    route_closures=[
        "QuantumBlockEncoding.BandedSparseAccess.accessMatrix_unitary",
        "QuantumBlockEncoding.BandedSparseAccess.primitiveAccess3_cleanAction",
        "QuantumBlockEncoding.BandedSparseAccess.primitiveAccess3Program_eval",
        "QuantumBlockEncoding.BandedSparseAccess.primitiveAccess3Program_unitary",
        "QuantumBlockEncoding.BandedSparseAccess.primitiveAccess3Program_oracleCalls_eq_zero",
    ],
),
            result(
                "QuantumBlockEncoding.BlockEncodingClassics.partialPermutationCertificate",
                "Partial-permutation certificate",
                "A finite partial permutation satisfying the declared support conditions yields an exact clean block.",
                r"A_{ij}\in\{0,1\},\quad \text{at most one supported entry per routed index}.",
                "The circuit route becomes finite index routing rather than dense matrix algebra.",
                "BE Case 1 can reuse this route and avoid an unconstrained circuit search.",
                ["QuantumBlockEncoding.BlockEncodingClassics.ExactCleanBlock"],
                "Construct the routed unitary and prove the clean ancilla block entry by entry.",
                [
                    ("Establish the finite routing conditions.", "partialPermutationCertificate"),
                    ("Read the clean block theorem.", "ExactCleanBlock.clean_eq_target"),
                ],
                "Compiled",
                "Compiled",
            ),
            result(
                "QuantumBlockEncoding.BlockEncodingClassics.productExactCleanBlockCertificate",
                "Product closure for exact clean blocks",
                "Compatible exact clean-block certificates compose into a certificate for the matrix product.",
                r"\operatorname{block}(U_B U_A)=BA.",
                "Certified components can be recombined as a proof-producing population operation.",
                "It is the formal counterpart of crossing over reusable constructions.",
                [
                    "QuantumBlockEncoding.BlockEncodingClassics.ExactCleanBlock",
                    "QuantumBlockEncoding.BlockEncodingClassics.matrix_mul_congr_pointwise",
                ],
                "Expand the projected product, use both component block identities, and reassociate finite sums.",
                [
                    ("Substitute component clean blocks.", "ExactCleanBlock.clean_eq_target"),
                    ("Identify the matrix product.", "matrix_mul_congr_pointwise"),
                ],
                "Compiled",
                "Compiled",
            ),
            result(
                "QuantumBlockEncoding.BlockEncodingClassics.QSVTConsumerContract",
                "QSVT consumer boundary",
                "The library records what a later QSVT stage may assume from a supplied block encoding.",
                r"U_A\leadsto p^{(\mathrm{SV})}(A/\alpha).",
                "QSVT is kept as an explicit consumer contract rather than treated as a proved end-to-end implementation.",
                "The hinted hard route can stop rediscovering the interface between a diagonal oracle and QSVT.",
                ["QuantumBlockEncoding.BlockEncodingClassics.HermitianDilationContract"],
                "Package the exact preconditions and expected transformed-operator relation as a typed boundary.",
                [
                    ("Provide a source block encoding.", "QSVTConsumerContract.source"),
                    ("State the consumer obligation.", "QSVTConsumerContract"),
                ],
                "Compiled",
                "Compiled",
                "None within the declared reusable route.",
                route_closures=[
                    "QuantumBlockEncoding.BlockEncodingClassics.QSVTConsumerContract.identity",
                    "QuantumBlockEncoding.BlockEncodingClassics.QSVTConsumerContract.identity_output",
                ],
            ),
        ],
    },
    {
        "slug": "certified-cases",
        "number": 7,
        "track": "Block encoding",
        "title": "Certified block-encoding cases",
        "summary": (
            "Distinguish completed local certificates from paper-facing contract "
            "models and historical experiments."
        ),
        "modules": [
            "QuantumBlockEncoding/ColdStartTransferE1.lean",
            "QuantumBlockEncoding/OptimalControl.lean",
            "QuantumBlockEncoding/CubicStatePreparation.lean",
            "QuantumBlockEncoding/GHL2025.lean",
            "QuantumBlockEncoding/Examples/RobinHeat.lean",
            "QuantumBlockEncoding/RobinMatrix.lean",
        ],
        "diagram": "roadmap",
        "results": [
            result(
                "QuantumBlockEncoding.coldE1Candidate_blockProjection",
                "BE Case 1 block projection",
                "The selected transfer-operator candidate has the required projected block.",
                r"\Pi U_{\mathrm{E1}}\Pi^\dagger=A_{\mathrm{E1}}/\alpha.",
                "The benchmark closes from a concrete candidate to the exact block identity.",
                "It is a compact reproducible example of the complete ASPBE acceptance path.",
                [
                    "QuantumBlockEncoding.coldE1CandidateImage_permutation_certificate",
                    "QuantumBlockEncoding.BlockEncodingClassics.partialPermutationCertificate",
                ],
                "Reuse the partial-permutation image certificate and simplify the selected entries.",
                [
                    ("Certify routed basis images.", "coldE1CandidateImage_permutation_certificate"),
                    ("Project the clean block.", "coldE1Candidate_blockProjection"),
                ],
                "Compiled",
                "Compiled",
            ),
            result(
                "QuantumBlockEncoding.CubicDiagonalOracle.cubicDiagonalHouseholderExactBEContract_complete",
                "BE Case 2 exact Householder completion",
                "The cubic diagonal benchmark has a completed exact block-encoding contract through the rational Householder route.",
                r"\Pi U_{\mathrm{cubic}}\Pi^\dagger=D_{\mathrm{cubic}}/\alpha.",
                "The hard benchmark converges by selecting a library-supported algebraic route, not by expanding a large gate fold.",
                "It records a completed alternative to the still-partial amplitude-oracle/QSVT route.",
                [
                    "QuantumBlockEncoding.CubicDiagonalOracle.linearDiagonalHouseholderInputBEContract_complete",
                    "QuantumBlockEncoding.CubicDiagonalOracle.cubicDiagonalRationalCompletion_backendSupport",
                ],
                "Complete the input Householder certificate, instantiate rational backend support, and package the cubic target identity.",
                [
                    ("Complete the linear input block.", "linearDiagonalHouseholderInputBEContract_complete"),
                    ("Supply rational backend support.", "cubicDiagonalRationalCompletion_backendSupport"),
                    ("Assemble the final certificate.", "cubicDiagonalHouseholderExactBEContract_complete"),
                ],
                "Compiled",
                "Compiled",
            ),
            result(
                "QuantumBlockEncoding.Examples.RobinHeat.oneTermRobinGamma3BoundaryUnitaryEntry_ne_backendFold_n3",
                "Robin raw-fold route is rejected",
                "The historical H-free symbolic entry is proved not equal to the proposed seven-slot backend fold.",
                r"U_{00}\ne\sum_{s=0}^{6} B_s.",
                "The all-one coefficient environment exposes a nonzero selected contribution that the old equality would force to zero.",
                "A proved counterexample closes this search branch and prevents future agents from spending budget on a false target.",
                [
                    "QuantumBlockEncoding.Examples.RobinHeat.oneTermRobinGamma3BoundaryBackendExpansionStatement_not_n3",
                    "QuantumBlockEncoding.Examples.RobinHeat.oneTermRobinGamma3BoundaryBackendExpansionStatement_equivUnitaryEntryFold_n3",
                ],
                "Assume the raw fold, convert it to the equivalent backend-expansion statement, and contradict the compiled all-one counterexample.",
                [
                    ("Assume the historical raw equality.", "intro hFold"),
                    ("Move to the equivalent expansion target.", "equivUnitaryEntryFold_n3.mpr"),
                    ("Apply the counterexample.", "BackendExpansionStatement_not_n3"),
                ],
                "Compiled",
                "Compiled",
                "The rejected branch is closed. The broader Robin paper reproduction remains experimental because several cited oracle contracts are not local gate-level certificates.",
            ),
        ],
    },
    {
        "slug": "resources-and-exports",
        "number": 8,
        "track": "System and evidence",
        "title": "Candidate comparison and executable exports",
        "summary": (
            "Keep formal validity lexicographically ahead of resource quality, "
            "then expose accepted candidates to executable tooling."
        ),
        "modules": [
            "QuantumBlockEncoding/Resources.lean",
            "QuantumBlockEncoding/BlockEncoding.lean",
            "QuantumBlockEncoding/Automation.lean",
            "QuantumBlockEncoding/PromiseGateOptimization.lean",
            "QuantumBlockEncoding/CubicAmplitudePrimitive.lean",
        ],
        "diagram": "candidate-lifecycle",
        "results": [
            result(
                "QuantumBlockEncoding.PromiseGateOptimization.controlledConjugation_matrix",
                "Control only the middle of a conjugation",
                "For a controlled V-dagger U V construction, V and V-dagger stay uncontrolled; only U receives the control.",
                r"C(V^\dagger U V)=(I\otimes V^\dagger)\,C(U)\,(I\otimes V).",
                "Both control branches agree: the false branch cancels V with V-dagger, and the true branch performs the conjugated target.",
                "This removes expensive controls and lets the outer operations use promise-register workspace.",
                [
                    "QuantumBlockEncoding.PromiseGateOptimization.controlledConjugation_equiv",
                    "QuantumBlockEncoding.Robin.ComplexLCU.equivPermutationMatrix_mul",
                ],
                "Prove the basis action by cases on the control bit, then lift the equivalence equality to permutation matrices.",
                [
                    ("Split the false and true control branches.", "cases control"),
                    ("Cancel the outer equivalence on the false branch.", "Equiv.symm_apply_apply"),
                    ("Compose the three permutation matrices.", "equivPermutationMatrix_mul"),
                ],
                "Compiled",
                "Compiled",
            ),
            result(
                "QuantumBlockEncoding.PromiseGateOptimization.dirtyControlledInvolution_action",
                "Replace a clean flag by a dirty flag",
                "If U squared is identity, compute-use-uncompute-use restores an arbitrary dirty flag and applies U exactly when requested.",
                r"U^2=I\Longrightarrow(c,b,|\psi\rangle)\mapsto(c,b,U^{[c]}|\psi\rangle).",
                "The extra controlled-U cancels the accidental application caused by an initially set dirty flag.",
                "It turns an ancilla-saving idea into a proof obligation that the planner can check before mutating a circuit.",
                [
                    "QuantumBlockEncoding.PromiseGateOptimization.dirtyControlledInvolutionEquiv",
                    "QuantumBlockEncoding.PromiseGateOptimization.dirtyControlledInvolution_unitary",
                ],
                "Case-split on the requested control and unknown dirty bit; use U(U(x))=x in the two cancellation branches.",
                [
                    ("Toggle the dirty flag with the predicate.", "toggleDirtyFlagEquiv"),
                    ("Use U under the flag twice.", "dirtyFlagControlledTargetEquiv"),
                    ("Apply involutivity to cancel accidental work.", "involutive"),
                    ("Read the exact clean/dirty cost tradeoff.", "dirtyFlag_replaces_cleanFlag"),
                ],
                "Compiled",
                "Compiled",
            ),
            result(
                "QuantumBlockEncoding.BlockEncodingCost.betterThan",
                "Lexicographic candidate comparison",
                "Two candidate costs are compared by a fixed, explicit priority order.",
                r"c_1\prec_{\mathrm{lex}}c_2.",
                "A smaller later metric never compensates for failing an earlier acceptance priority.",
                "Population maintenance and promotion must be reproducible across runs.",
                ["QuantumBlockEncoding.BlockEncodingCost"],
                "Compare the first differing coordinate in the declared score tuple.",
                [
                    ("Build both score records.", "BlockEncodingCost"),
                    ("Apply the fixed ordering.", "BlockEncodingCost.betterThan"),
                ],
                "Compiled",
                "Compiled",
            ),
result(
    "QuantumBlockEncoding.CubicDiagonalOracle.cubicN2PrimitiveVerifiedBlockEncoding",
    "Finite cubic amplitude oracle",
    "A four-way uniformly controlled RY circuit exactly block-encodes the two-qubit cubic diagonal operator.",
    r"\Pi_0U_{\mathrm{cubic},2}\Pi_0^\dagger=\operatorname{diag}(0,(1/4)^3,(2/4)^3,(3/4)^3).",
    "Each system basis string selects the exact angle 2 arccos((j/4)^3); the clean RY entry is therefore the desired diagonal amplitude.",
    "The earlier opaque one-call tuple remains a diagnostic, but the accepted teaching route now has gate-expanded semantics, exact clean projection, and a verified block-encoding wrapper.",
    [
        "QuantumBlockEncoding.compileUniformlyControlledRy_eval_controlledRyBlockMatrix",
        "QuantumBlockEncoding.CubicDiagonalOracle.cubicN2PrimitiveProgram_cleanEntry",
        "QuantumBlockEncoding.CubicDiagonalOracle.cubicN2PrimitiveFlatUnitary_unitary",
    ],
    "Compile the four exact amplitudes through the uniformly controlled RY theorem, prove the clean entries, reindex the little-endian basis, and package the resulting unitary as a verified block encoding.",
    [
        ("Select one exact cubic amplitude.", "cubicN2Angle"),
        ("Compile the multiplexed rotations.", "cubicN2PrimitiveCircuit_eval"),
        ("Prove the clean diagonal entry.", "cubicN2PrimitiveProgram_cleanEntry"),
        ("Promote the flat unitary and block.", "cubicN2PrimitiveVerifiedBlockEncoding"),
    ],
    "Compiled",
    "Compiled",
    "None within the fixed n=2 primitive route. Scalable arithmetic and general QSVT phase synthesis remain separately scoped research routes.",
    route_closures=[
        "QuantumBlockEncoding.CubicDiagonalOracle.cubicN2PrimitiveProgram_cleanEntry",
        "QuantumBlockEncoding.CubicDiagonalOracle.cubicN2PrimitiveFlatUnitary_unitary",
        "QuantumBlockEncoding.CubicDiagonalOracle.cubicN2PrimitiveFlatUnitary_cleanBlock",
        "QuantumBlockEncoding.CubicDiagonalOracle.cubicN2PrimitiveVerifiedBlockEncoding",
        "QuantumBlockEncoding.CubicDiagonalOracle.cubicN2Primitive_oracleCalls_eq_zero",
    ],
),
        ],
    },
    {
        "slug": "automation-and-roadmap",
        "number": 9,
        "track": "System and evidence",
        "title": "Search control, evidence, and open work",
        "summary": (
            "Show how typed stages, agent layers, candidate populations, proof "
            "gates, and explicit open problems coordinate without overstating evidence."
        ),
        "modules": [
            "QuantumBlockEncoding/Automation.lean",
            "QuantumBlockEncoding/AutomationTrace.lean",
            "QuantumBlockEncoding/Literature.lean",
            "QuantumBlockEncoding/OpenProblems.lean",
            "QuantumBlockEncoding/OpenProblemsAudit.lean",
        ],
        "diagram": "candidate-lifecycle",
        "results": [
result(
    "QuantumBlockEncoding.threeLayerAgentContracts",
    "Three-layer agent contracts",
    "The harness records distinct responsibilities and a typed, executable handoff state machine for planning, refinement, proof work, and review.",
    r"\text{upper}\rightarrow\text{middle}\rightarrow\text{lower}\rightarrow\text{reviewer}\rightarrow\text{accepted}.",
    "Every handoff must be logged and carry an artifact; acceptance additionally requires both the Lean gate and reviewer approval.",
    "Hard tasks need explicit ownership and machine-checkable promotion conditions instead of repeated untracked prompts.",
    [
        "QuantumBlockEncoding.AutomationStage",
        "QuantumBlockEncoding.AutomationTask",
        "QuantumBlockEncoding.ThreeLayerTrace",
    ],
    "Encode role contracts as data, define an executable transition guard, and prove that the canonical trace reaches acceptance while a failed Lean gate cannot do so.",
    [
        ("Declare stage and task types.", "AutomationStage / AutomationTask"),
        ("Instantiate layer contracts.", "threeLayerAgentContracts"),
        ("Check every typed handoff.", "threeLayerCanonicalTrace_allValid"),
        ("Require Lean and reviewer approval.", "threeLayerAccepted_requiresLeanGate"),
    ],
    "Compiled",
    "Compiled",
    "None within the typed handoff and acceptance route. Running external models remains engineering evidence rather than a Lean theorem.",
    route_closures=[
        "QuantumBlockEncoding.threeLayerCanonicalTrace_allValid",
        "QuantumBlockEncoding.threeLayerCanonicalTrace_reachesAccepted",
        "QuantumBlockEncoding.threeLayerAccepted_requiresLeanGate",
        "QuantumBlockEncoding.threeLayerAccepted_requiresReviewerApproval",
        "QuantumBlockEncoding.threeLayerFailedGateTrace_notAccepted",
    ],
),
result(
    "QuantumBlockEncoding.openProblems",
    "Open problems are first-class data",
    "Unfinished mathematical or engineering routes are listed explicitly with stable identifiers, status, evidence requirements, and source references.",
    r"\mathcal O=[o_1,\ldots,o_7],\qquad \operatorname{Nodup}(\operatorname{id}(\mathcal O)).",
    "A planned result cannot be mistaken for a theorem merely because it appears near compiled code.",
    "The registry route is itself audited even though the mathematical problems it contains intentionally remain open.",
    [
        "QuantumBlockEncoding.OpenProblem",
        "QuantumBlockEncoding.openProblemIds",
    ],
    "Publish the typed records, prove that their identifiers are unique, and check that every entry has a nonempty statement, acceptance test, and reference list.",
    [
        ("Describe each obligation.", "OpenProblem"),
        ("Publish the current list.", "openProblems"),
        ("Check stable unique identifiers.", "openProblemIds_nodup"),
        ("Check actionable evidence fields.", "openProblems_all_actionable"),
    ],
    "Compiled",
    "Compiled",
    "The registry route is closed; its seven mathematical problems remain intentionally open and are not presented as solved theorems.",
    route_closures=[
        "QuantumBlockEncoding.openProblems_count",
        "QuantumBlockEncoding.openProblemIds_nodup",
        "QuantumBlockEncoding.openProblems_all_actionable",
        "QuantumBlockEncoding.openProblemRegistry_compiled",
    ],
),
        ],
    },
]

CHAPTERS.sort(key=lambda chapter: int(chapter["number"]))


# Continuous teaching prose sits beside, rather than inside, declaration cards.
# The quantum-computing exposition follows the order and conventions of Lin's
# lecture notes (arXiv:2201.08309), with ASPBE-specific formal checkpoints.
LESSONS = {
    "linear-algebra": {
        "lead": "A quantum state is a complex column vector. For n qubits its dimension is 2^n, so every basis label is a finite index from 0 to 2^n-1.",
        "objectives": [
            "Read ket notation as an ordinary finite vector.",
            "Check dimensions before manipulating a circuit or matrix.",
            "Distinguish vector normalization from matrix unitarity.",
        ],
        "sections": [
            ("States are normalized vectors", r"|\psi\rangle=\sum_{j=0}^{2^n-1}\psi_j|j\rangle,\qquad \sum_j|\psi_j|^2=1.", "The amplitudes are complex numbers and the squared magnitudes sum to one. An unnormalized data vector must be rescaled before it can be the exact output of a unitary."),
            ("Matrices act on columns", r"(U|\psi\rangle)_i=\sum_j U_{ij}\psi_j.", "ASPBE fixes column-vector, left-action semantics. This convention determines gate order, first-column state preparation, and clean-block indices."),
            ("Equality becomes finite obligations", r"A=B\iff \forall i,j,\ A_{ij}=B_{ij}.", "Lean does not accept a diagram as evidence. It checks each finite index, or a reusable theorem that implies all of those entry equalities."),
        ],
        "checkpoint": "Before continuing, be able to explain why a one-qubit gate is a 2 by 2 matrix and a two-qubit gate is a 4 by 4 matrix.",
    },
    "circuit-semantics": {
        "lead": "A circuit is an ordered program; its denotation is one unitary matrix. The list order and multiplication order must be stated once and then reused everywhere.",
        "objectives": [
            "Read a gate list from input to output.",
            "Relate sequential gates to a matrix product.",
            "Track which bits belong to each register.",
        ],
        "sections": [
            ("Unitary evolution", r"U^\dagger U=I,\qquad |\psi'\rangle=U|\psi\rangle.", "A gate preserves norm. ASPBE's concrete certificates use Mathlib's unitary group, while symbolic paper models keep unproved oracle unitarity as an explicit contract."),
            ("Composition order", r"[g_1,g_2,\ldots,g_m]\mapsto G_m\cdots G_2G_1.", "The rightmost matrix acts first. Reversing this convention can preserve dimensions while changing the algorithm, so the evaluator is a named library definition."),
            ("Registers are part of meaning", r"|a\rangle|i\rangle\leftrightarrow a\,2^n+i.", "Flattening ancilla and system registers requires one fixed order. Projection lemmas prove that the flat index and product-register views select the same entries."),
        ],
        "checkpoint": "Given gates G then V, write the final state and the combined matrix without reversing their order.",
    },
    "state-preparation": {
        "lead": "State preparation asks for one observable action: start in the all-zero basis state and end at a specified normalized target.",
        "objectives": [
            "State the target contract independently of block encoding.",
            "Verify normalization, unitarity, and state action separately.",
            "Follow the X and Hadamard examples through complete Lean certificates.",
        ],
        "sections": [
            ("The contract", r"U|0^n\rangle=|\psi\rangle.", "The input is fixed, but U must still be a unitary on the whole 2^n-dimensional space. Specifying only the desired output vector is not yet a circuit."),
            ("Pauli X", r"X=\begin{pmatrix}0&1\\1&0\end{pmatrix},\qquad X|0\rangle=|1\rangle.", "X exchanges the two computational-basis states. The formal example represents X as Mathlib's swap matrix and obtains unitarity from self-invertibility."),
            ("Hadamard", r"H=\frac1{\sqrt2}\begin{pmatrix}1&1\\1&-1\end{pmatrix},\qquad H|0\rangle=|+\rangle.", "The plus state has two equal amplitudes. Lean separately proves the square-root normalization, H's unitary equation, and the zero-state action."),
        ],
        "checkpoint": "Open both complete certificates below and identify the exact line that proves normalization, unitarity, and preparation.",
    },
    "state-preparation-certificates": {
        "lead": "A certificate is useful because later code can consume one trusted object instead of repeating the matrix calculation.",
        "objectives": [
            "See why the zero-state equation is a first-column equation.",
            "Read the fields of a verified preparation record.",
            "Reuse exact evidence in a zero-error approximate interface.",
        ],
        "sections": [
            ("Why column zero appears", r"U|0^n\rangle=\operatorname{column}_0(U).", "The zero ket has one nonzero amplitude at index zero. Matrix-vector multiplication therefore discards every column except the first."),
            ("What the record stores", r"\text{normalized target}+\text{unitary U}+\text{first-column proof}.", "Each field has a different failure mode. Keeping them separate prevents a correct first column from hiding a nonunitary completion."),
            ("Exact before approximate", r"\varepsilon=0\Rightarrow \|U|0^n\rangle-|\psi\rangle\|=0.", "An exact certificate can enter an approximate search unchanged. Positive error needs a declared metric and a new bound."),
        ],
        "checkpoint": "Explain why matching column zero alone does not prove that a candidate is physically implementable.",
    },
    "block-encoding": {
        "lead": "Block encoding is an input model for a generally nonunitary matrix: a larger unitary exposes the desired operator when clean ancillas are projected onto zero.",
        "objectives": [
            "Read the roles of U, the ancillas, alpha, and epsilon.",
            "Translate the projector equation into indexed matrix entries.",
            "Understand why a very large alpha is mathematically valid but operationally costly.",
        ],
        "sections": [
            ("Exact clean block", r"(\langle0^a|\otimes I)U(|0^a\rangle\otimes I)=A/\alpha.", "The upper-left wording is safe only after register order is fixed. ASPBE therefore records the clean index and layout as part of the contract."),
            ("Proof style A: project the matrix", r"\langle0^a,i|U|0^a,j\rangle=(A/\alpha)_{ij}.", "This is the direct form of Definition 1, Eq. (2), in arXiv:2205.00081. It is usually the shortest Lean proof for a finite circuit: fix i and j, unfold the clean register indices, and prove one matrix entry."),
            ("Proof style B: follow an arbitrary input", r"U|0^a\rangle|\psi\rangle=|0^a\rangle\widetilde A|\psi\rangle+\sqrt{1-\|\widetilde A|\psi\rangle\|^2}\,|\sigma_\perp\rangle.", "Equations (3)-(5) of arXiv:2205.00081 express the same clean block through state evolution: the failure state has zero clean projection and unit norm. ASPBE proves the basis-action/projected-entry equivalence; linearity gives arbitrary inputs. A claimed normalized failure branch still needs its own unitarity and norm proof."),
            ("Approximate form", r"\|A-\alpha(\langle0^a|\otimes I)U(|0^a\rangle\otimes I)\|\le\varepsilon.", "The norm and tolerance must be named. Approximation is a controlled relaxation, not permission to change the target matrix."),
            ("Normalization affects success", r"p(0^a)=\|A|b\rangle\|^2/\alpha^2.", "A larger alpha can make unitary completion easier but lowers clean-ancilla success probability. Resource comparisons must report it."),
        ],
        "checkpoint": "For a proposed U, write the exact row and column indices selected when every ancilla is zero.",
    },
    "classic-routes": {
        "lead": "Most useful proofs follow a small number of constructions. Route selection should happen before expanding a large circuit product.",
        "objectives": [
            "Recognize permutation, sparse, LCU, product, and dilation routes.",
            "Reuse a completed leaf instead of reproving finite-sum algebra.",
            "Treat QSVT as a consumer of a valid block encoding.",
        ],
        "sections": [
            ("Sparse routing", r"O_c|j\rangle=|c(j)\rangle.", "When support is a reversible finite map, the proof reduces to routed basis indices and vanishing off-support entries."),
            ("Banded sparse access", r"U_A^{(l)}:|0^{n-l}\rangle|s\rangle\mapsto|r_{s0}\rangle,\qquad U^{SUM}:|r\rangle|i\rangle\mapsto|r+i\bmod2^n\rangle|i\rangle.", "ASPBE proves the arbitrary-size semantic composition and its unitary permutation matrix. The source paper's general resource formula remains a separate compiler theorem."),
            ("Composition", r"\operatorname{block}(U_BU_A)=BA.", "Compatible clean-block certificates compose. Register compatibility and normalizers still have to match."),
            ("Consumer boundary", r"U_A\leadsto p^{(\mathrm{SV})}(A/\alpha).", "QSVT does not repair an invalid source encoding. The source certificate and the polynomial approximation are separate proof obligations."),
        ],
        "checkpoint": "Choose one route for a diagonal matrix and state which oracle or finite map must still be implemented.",
    },
    "certified-cases": {
        "lead": "Case studies show both successful certificates and rejected routes. A refutation is a completed result when it prevents reuse of a false premise.",
        "objectives": [
            "Trace BE Case 1 and BE Case 2 to their accepted roots.",
            "Separate a compiled paper-model lemma from a paper-wide reproduction.",
            "Read the Robin counterexample as reusable failure memory.",
        ],
        "sections": [
            ("Accepted cases", r"\text{candidate}\rightarrow\text{unitary proof}\rightarrow\text{clean block}\rightarrow\text{cost}.", "BE Case 1 uses finite permutation structure. BE Case 2 uses an exact rational Householder completion. Both end at named compiled roots."),
            ("Robin audit closure", r"U_{00}\ne\sum_s B_s\quad\text{for the historical H-free target}.", "The raw symbolic route is not merely slow: the current target is false. Lean proves the contradiction through a concrete coefficient environment."),
            ("What remains experimental", r"\text{paper theorem}=\text{local semantics}+\text{cited oracle contracts}.", "The research module now has zero proof holes, but several external oracle constructions are still typed assumptions rather than local gate-level certificates."),
        ],
        "checkpoint": "Check both badges: a local theorem may compile while a larger paper route remains experimental.",
    },
    "resources-and-exports": {
        "lead": "Correctness is a gate; resource quality ranks only candidates that pass it.",
        "objectives": [
            "Read a lexicographic cost tuple.",
            "Distinguish logical-gate and backend-transpiled costs.",
            "Understand what executable validation can and cannot certify.",
        ],
        "sections": [
            ("Lexicographic ranking", r"(g,d,a,o)_1<_{\rm lex}(g,d,a,o)_2.", "The first differing coordinate decides. A low-depth invalid circuit never outranks a valid certificate."),
            ("Promise registers as a proved optimization rule", r"C(V^\dagger U V)=(I\otimes V^\dagger)C(U)(I\otimes V).", "ASPBE proves the controlled-conjugation identity from arXiv:2603.12917 as an exact finite permutation-matrix theorem. The planner may remove controls from V and V-dagger only after matching register order and target semantics."),
            ("Dirty helper for an involution", r"U^2=I:\quad\mathrm{toggle};C(U);\mathrm{toggle};C(U).", "ASPBE also proves that this protocol restores an arbitrary dirty flag and costs one extra controlled-U compared with the clean-flag construction. Concrete candidates still owe the involution, promise, restoration, and same-tier resource proofs."),
            ("Executable checks", r"\text{Lean certificate}+\text{finite export}+\text{backend report}.", "Qiskit or QASM tests catch convention and implementation errors, but numerical agreement is not substituted for the symbolic theorem."),
        ],
        "checkpoint": "Identify which cost coordinates are proved from the logical circuit and which depend on a selected hardware backend.",
    },
    "automation-and-roadmap": {
        "lead": "ASPBE treats proof search as a controlled scientific process: freeze the contract, retrieve memory, test distinct routes, and promote only verified evidence.",
        "objectives": [
            "Understand upper, middle, lower, verifier, and reviewer responsibilities.",
            "See how failed routes become searchable memory.",
            "Interpret roadmap statuses without confusing plans with theorems.",
        ],
        "sections": [
            ("Decompose before scaling", r"\text{goal}\rightarrow\text{proof DAG}\rightarrow\text{ready leaves}.", "Parallel agents are added only when there are independent ready obligations or meaningfully different construction families."),
            ("Feedback changes the next action", r"\text{counterexample}\Rightarrow\text{retire parent route}.", "Repeated identical failures do not justify more budget. The middle layer records the obstruction, updates the population, and chooses a new route or an adjacent tolerance tier."),
            ("Status is evidence", r"\text{Compiled}\ne\text{paper-wide complete}.", "The site reports local compilation and broader route completion independently. CI regenerates counts and rejects proof holes."),
        ],
        "checkpoint": "For any roadmap item, locate its declaration, its current evidence, and the one missing step before assigning another agent.",
    },
}


IMPLEMENTATION_MAP = [
    {
        "goal": "Prepare the one-qubit plus state",
        "contract": r"H|0\rangle=(|0\rangle+|1\rangle)/\sqrt2",
        "obligation": "Normalization, Mathlib unitarity, state action, and logical cost",
        "declaration": "QuantumBlockEncoding.TextbookStatePreparation.hadamardCertificate_prepares_plus",
        "dependencies": "hadamard_unitary; plusTarget_normalized; hadamard_prepares_plus",
        "status": "Compiled",
        "missing": "None for this textbook route",
        "chapter": "state-preparation",
    },
    {
        "goal": "Prepare the one-qubit basis state one",
        "contract": r"X|0\rangle=|1\rangle",
        "obligation": "Permutation unitarity, state action, and logical cost",
        "declaration": "QuantumBlockEncoding.TextbookStatePreparation.pauliXCertificate_prepares_one",
        "dependencies": "pauliX_unitary; oneTarget_normalized; pauliX_prepares_one",
        "status": "Compiled",
        "missing": "None for this textbook route",
        "chapter": "state-preparation",
    },
    {
        "goal": "Prepare a finite target state",
        "contract": r"U|0^n\rangle=|\psi\rangle",
        "obligation": "Normalization, unitarity, and first-column equality supplied to the promotion constructor",
        "declaration": "QuantumBlockEncoding.StatePreparationCandidate.preparesTarget",
        "dependencies": "StatePreparationCandidate.certify; textbook Pauli-X and Hadamard witnesses",
        "status": "Compiled",
        "missing": "None for the reusable promotion route; each new target family supplies its own proof terms",
        "chapter": "state-preparation",
    },
    {
        "goal": "Consume a verified prepared state",
        "contract": r"U_{i0}=\psi_i",
        "obligation": "First-column projection",
        "declaration": "QuantumBlockEncoding.VerifiedStatePreparation.firstColumn",
        "dependencies": "VerifiedStatePreparation",
        "status": "Compiled",
        "missing": "None locally",
        "chapter": "state-preparation-certificates",
    },
    {
        "goal": "Read first-column evidence as state action",
        "contract": r"\operatorname{column}_0(U)=\psi\iff U|0^n\rangle=|\psi\rangle",
        "obligation": "Finite basis-ket matrix-action bridge",
        "declaration": "QuantumBlockEncoding.ConcreteSemantics.firstColumnMatches_iff_applyVec_zeroKet",
        "dependencies": "FirstColumnMatches; applyVec_zeroKet",
        "status": "Compiled",
        "missing": "Candidate normalization and unitarity remain separate",
        "chapter": "state-preparation-certificates",
    },
    {
        "goal": "Evaluate a gate list",
        "contract": r"\llbracket C\rrbracket=G_m\cdots G_1",
        "obligation": "Fixed fold and register order",
        "declaration": "QuantumBlockEncoding.evalGateMatrices",
        "dependencies": "GateMatrix; Matrix",
        "status": "Compiled",
        "missing": "None locally",
        "chapter": "circuit-semantics",
    },
    {
        "goal": "Extract a block from a circuit",
        "contract": r"\Pi U\Pi^\dagger=A/\alpha",
        "obligation": "Typed circuit semantics, selected projection equality, and finite identity witness",
        "declaration": "QuantumBlockEncoding.CircuitMatrixSemantics.blockExtractionTarget",
        "dependencies": "CertifiedCircuitBlockExtraction; teachingIdentityBlockExtraction",
        "status": "Compiled",
        "missing": "None for the reusable extraction route; each concrete circuit supplies its unitary and entry proof",
        "chapter": "circuit-semantics",
    },
    {
        "goal": "Move between flat and product-register block views",
        "contract": r"\Pi_s U\Pi_s^\dagger=\operatorname{cleanBlockProduct}(s,U)",
        "obligation": "Shared register-order projection equality",
        "declaration": "QuantumBlockEncoding.ConcreteSemantics.signalSystemBlockProjection_eq_cleanBlockProduct",
        "dependencies": "signalSystemBlockProjection; cleanBlockProduct",
        "status": "Compiled",
        "missing": "Candidate-level block and unitarity proofs remain separate",
        "chapter": "circuit-semantics",
    },
    {
        "goal": "Package an exact block encoding",
        "contract": r"\Pi U\Pi^\dagger=A/\alpha",
        "obligation": "Candidate unitarity and exact block identity supplied to the promotion constructor",
        "declaration": "QuantumBlockEncoding.VerifiedOperatorBlockEncoding",
        "dependencies": "OperatorBlockEncodingCandidate.certify; certified finite cases",
        "status": "Compiled",
        "missing": "None for the reusable promotion route; concrete candidate fields remain route-specific inputs",
        "chapter": "block-encoding",
    },
    {
        "goal": "Reuse an exact certificate approximately",
        "contract": r"\|A-\alpha\Pi U\Pi^\dagger\|=0",
        "obligation": "Zero-error conversion",
        "declaration": "QuantumBlockEncoding.VerifiedOperatorBlockEncoding.asZeroErrorApprox",
        "dependencies": "VerifiedOperatorBlockEncoding",
        "status": "Compiled",
        "missing": "Positive-error analyses are route-specific",
        "chapter": "block-encoding",
    },
    {
        "goal": "Certify a partial permutation",
        "contract": r"\operatorname{block}(U)=A",
        "obligation": "Finite routed-entry proof",
        "declaration": "QuantumBlockEncoding.BlockEncodingClassics.partialPermutationCertificate",
        "dependencies": "ExactCleanBlock",
        "status": "Compiled",
        "missing": "None locally",
        "chapter": "classic-routes",
    },
    {
        "goal": "Compose exact block encodings",
        "contract": r"\operatorname{block}(U_BU_A)=BA",
        "obligation": "Projected product equality",
        "declaration": "QuantumBlockEncoding.BlockEncodingClassics.productExactCleanBlockCertificate",
        "dependencies": "ExactCleanBlock; matrix_mul_congr_pointwise",
        "status": "Compiled",
        "missing": "Register compatibility for each application",
        "chapter": "classic-routes",
    },
    {
        "goal": "Close BE Case 1",
        "contract": r"\Pi U_{\mathrm{E1}}\Pi^\dagger=A_{\mathrm{E1}}/\alpha",
        "obligation": "Transfer-operator projection",
        "declaration": "QuantumBlockEncoding.coldE1Candidate_blockProjection",
        "dependencies": "coldE1CandidateImage_permutation_certificate",
        "status": "Compiled",
        "missing": "None locally",
        "chapter": "certified-cases",
    },
    {
        "goal": "Close BE Case 2",
        "contract": r"\Pi U_{\mathrm{cubic}}\Pi^\dagger=D/\alpha",
        "obligation": "Exact rational Householder completion",
        "declaration": "QuantumBlockEncoding.CubicDiagonalOracle.cubicDiagonalHouseholderExactBEContract_complete",
        "dependencies": "Householder input; rational backend support",
        "status": "Compiled",
        "missing": "None for the selected exact route",
        "chapter": "certified-cases",
    },
    {
        "goal": "Feed a certified clean block to a typed polynomial consumer",
        "contract": r"U_D\leadsto p^{(\mathrm{SV})}(D/\alpha)",
        "obligation": "Source certificate, side conditions, and a finite degree-one identity realization",
        "declaration": "QuantumBlockEncoding.BlockEncodingClassics.QSVTConsumerContract",
        "dependencies": "QSVTConsumerContract.identity; teachingIdentityQSVTConsumer",
        "status": "Compiled",
        "missing": "None for the typed identity consumer; general phase synthesis and approximation checking remain roadmap items",
        "chapter": "classic-routes",
    },
    {
        "goal": "Compile a finite banded sparse-access witness",
        "contract": r"|s\rangle|i\rangle|0\rangle\mapsto|s\oplus3+i\bmod8\rangle|i\rangle|0\rangle",
        "obligation": "Primitive refinement, clean workspace, unitarity, and zero oracle calls",
        "declaration": "QuantumBlockEncoding.BandedSparseAccess.primitiveAccess3Program_eval",
        "dependencies": "modularAdd3ReversibleProgram; compileReversibleProgram_eval",
        "status": "Compiled",
        "missing": "Arbitrary-width source gate upper bounds remain a separate compiler theorem",
        "chapter": "classic-routes",
    },
    {
        "goal": "Compile a finite cubic diagonal amplitude oracle",
        "contract": r"\Pi_0U\Pi_0^\dagger=\operatorname{diag}((j/4)^3)",
        "obligation": "Exact multiplexed RY semantics, clean projection, and verified BE packaging",
        "declaration": "QuantumBlockEncoding.CubicDiagonalOracle.cubicN2PrimitiveVerifiedBlockEncoding",
        "dependencies": "UniformlyControlledRy; PrimitiveBasisLE; exact RY bridge",
        "status": "Compiled",
        "missing": "Scalable arithmetic and general QSVT phase synthesis are separate routes",
        "chapter": "resources-and-exports",
    },
    {
        "goal": "Verify three-layer harness promotion",
        "contract": r"\text{upper}\to\text{middle}\to\text{lower}\to\text{reviewer}\to\text{accepted}",
        "obligation": "Logged artifacts, valid role order, Lean gate, and reviewer approval",
        "declaration": "QuantumBlockEncoding.threeLayerCanonicalTrace_reachesAccepted",
        "dependencies": "ThreeLayerHandoff.validFlag; ThreeLayerTrace.finalPhase",
        "status": "Compiled",
        "missing": "External model execution remains engineering evidence",
        "chapter": "automation-and-roadmap",
    },
    {
        "goal": "Audit the open-problem registry",
        "contract": r"|\mathcal O|=7\land\operatorname{Nodup}(\operatorname{id}(\mathcal O))",
        "obligation": "Unique identifiers and nonempty actionable fields",
        "declaration": "QuantumBlockEncoding.openProblemRegistry_compiled",
        "dependencies": "openProblemIds_nodup; openProblems_all_actionable",
        "status": "Compiled",
        "missing": "The registered mathematical problems intentionally remain open",
        "chapter": "automation-and-roadmap",
    },
    {
        "goal": "Close the historical Robin raw-fold branch",
        "contract": r"U_{00}\ne\sum_s B_s",
        "obligation": "Convert the raw fold to the refuted backend expansion",
        "declaration": "QuantumBlockEncoding.Examples.RobinHeat.oneTermRobinGamma3BoundaryUnitaryEntry_ne_backendFold_n3",
        "dependencies": "Equivalence bridge; all-one counterexample",
        "status": "Compiled",
        "missing": "None for the rejected branch; cited oracle implementations remain experimental",
        "chapter": "certified-cases",
    },
]


ROADMAP = [
    ("State-preparation contracts and first-column consumer", "Compiled"),
    ("Textbook Pauli X and Hadamard certificates", "Compiled"),
    ("Circuit syntax to matrix semantics", "Compiled"),
    ("Reusable exact block-encoding routes", "Compiled"),
    ("Finite three-bit primitive banded sparse access", "Compiled"),
    ("BE Case 1 transfer-operator certificate", "Compiled"),
    ("BE Case 2 exact Householder certificate", "Compiled"),
    ("Finite two-qubit cubic primitive amplitude oracle", "Compiled"),
    ("Degree-one QSVT identity consumer realization", "Compiled"),
    ("Three-layer controller trace and registry audit", "Compiled"),
    ("Fixed-N8 Robin T3 reproduction and evolved winner", "Compiled"),
    ("Arbitrary-width banded-access source resource compiler", "Planned"),
    ("General QSVT phase synthesis and approximation checker", "Planned"),
    ("Arbitrary-n GHL and full Hamiltonian reproduction", "Experimental"),
    ("Historical Robin H-free raw-fold rejection", "Compiled"),
]


WORKFLOW_STAGES = [
    (
        "1. Formal target",
        "Translate the mathematical request into a state-preparation or block-projection contract.",
    ),
    (
        "2. Memory retrieval",
        "Retrieve compatible completed declarations, route cards, and known obstructions.",
    ),
    (
        "3. Candidate population",
        "Generate distinct constructions and retain provenance, assumptions, and resource tuples.",
    ),
    (
        "4. Resource ranking",
        "Apply the declared lexicographic score without promoting an invalid candidate.",
    ),
    (
        "5. Lean obligations",
        "Split unitarity, dimensions, register order, projection, normalization, and approximation goals.",
    ),
    (
        "6. Adaptive exploration",
        "The upper layer may add agents, recombine routes, or relax epsilon only from recorded feedback.",
    ),
    (
        "7. Acceptance gate",
        "Require the Lean build, tests, no-new-proof-hole policy, and source-linked documentation.",
    ),
    (
        "8. Executable validation",
        "Run applicable circuit or matrix exports, including Qiskit checks, after the formal certificate gate.",
    ),
]
