const taskName = document.getElementById("taskName");
const mode = document.getElementById("mode");
const languagePreset = document.getElementById("languagePreset");
const languageCustom = document.getElementById("languageCustom");
const oracleDescription = document.getElementById("oracleDescription");
const normalizer = document.getElementById("normalizer");
const projector = document.getElementById("projector");
const baseline = document.getElementById("baseline");
const constraints = document.getElementById("constraints");
const upperBackend = document.getElementById("upperBackend");
const middleBackend = document.getElementById("middleBackend");
const lower1Backend = document.getElementById("lower1Backend");
const lower2Backend = document.getElementById("lower2Backend");
const lower3Backend = document.getElementById("lower3Backend");
const reviewerBackend = document.getElementById("reviewerBackend");
const packet = document.getElementById("packet");
const copyStatus = document.getElementById("copyStatus");

function selectedLanguage() {
  if (languagePreset.value === "custom") {
    return languageCustom.value.trim() || "custom";
  }
  return languagePreset.value;
}

function modeDescription(value) {
  const descriptions = {
    operatorBlockEncoding:
      "Construct and evolve a block encoding for a user-specified operator.",
    paperBenchmark:
      "Faithfully reproduce a paper construction before any improvement search.",
    exploratoryConstruction:
      "Improve a known correct construction under a fixed operator target.",
  };
  return descriptions[value] || descriptions.operatorBlockEncoding;
}

function backendCommand(value) {
  const commands = {
    codex:
      'cd {root} && codex exec --dangerously-bypass-approvals-and-sandbox "$(cat {prompt})"',
    claude:
      'cd {root} && claude -p --permission-mode bypassPermissions "$(cat {prompt})"',
    gpt:
      'cd {root} && bash tools/vendor_agent_wrapper.example.sh gpt "{prompt}"',
    gemini:
      'cd {root} && bash tools/vendor_agent_wrapper.example.sh gemini "{prompt}"',
    glm:
      'cd {root} && bash tools/vendor_agent_wrapper.example.sh glm "{prompt}"',
    minimax:
      'cd {root} && bash tools/vendor_agent_wrapper.example.sh minimax "{prompt}"',
    custom:
      'cd {root} && bash tools/vendor_agent_wrapper.example.sh custom "{prompt}"',
  };
  return commands[value] || commands.custom;
}

function backendProfileJson() {
  return JSON.stringify(
    {
      commands: {
        upper: backendCommand(upperBackend.value),
        middle: backendCommand(middleBackend.value),
        lower1: backendCommand(lower1Backend.value),
        lower2: backendCommand(lower2Backend.value),
        lower3: backendCommand(lower3Backend.value),
        reviewer: backendCommand(reviewerBackend.value),
      },
      selectedBackends: {
        upper: upperBackend.value,
        middle: middleBackend.value,
        lower1: lower1Backend.value,
        lower2: lower2Backend.value,
        lower3: lower3Backend.value,
        reviewer: reviewerBackend.value,
      },
    },
    null,
    2,
  );
}

function buildPacket() {
  const lang = selectedLanguage();
  const title = taskName.value.trim() || "operator-block-encoding-task";
  const date = new Date().toISOString();
  const md = `# ABEIS Task Packet: ${title}

Generated by the static web task builder at ${date}.

## Mode

- Mode: \`${mode.value}\`
- Meaning: ${modeDescription(mode.value)}
- Preferred human report language: \`${lang}\`

## Agent Backend Preferences

The web page does not call model APIs.  It records the user's preferred model
backend for each ABEIS role.  The local harness should map these preferences
to installed CLIs or wrappers.

\`\`\`json
${backendProfileJson()}
\`\`\`

## Operator Contract

Target operator or oracle requirement:

\`\`\`latex
${oracleDescription.value.trim() || "TBD"}
\`\`\`

Normalizer:

\`\`\`text
alpha = ${normalizer.value.trim() || "TBD"}
\`\`\`

Block projector / clean state:

\`\`\`text
${projector.value.trim() || "TBD"}
\`\`\`

Known baseline construction:

\`\`\`text
${baseline.value.trim() || "None supplied."}
\`\`\`

Constraints, free parameters, source links, and non-goals:

\`\`\`text
${constraints.value.trim() || "TBD"}
\`\`\`

## Required ABEIS Discipline

1. Fix the mathematical target before candidate search.
2. Keep natural-language proof plans separate from Lean-certified claims.
3. A candidate enters the certified population only after Lean proves:
   - the candidate matrix/unitary is unitary in the chosen semantics;
   - the requested block-entry equation equals the target operator divided by \`alpha\`;
   - the resource record matches the circuit schedule.
4. Necessary-condition checks may reject candidates early, but may not certify them.
5. Compare asymptotic tiers first.  Inside one tier, use the concrete tuple:

\`\`\`text
(gateCount, depth, auxiliaryQubits, oracleCalls)
\`\`\`

## Suggested Agent Packet

- Upper target auditor: check the operator, normalizer, projector, free parameters, and whether the task is paper-faithful or exploratory.
- Upper proof-DAG strategist: choose the minimal theorem leaf needed for the first Lean certificate.
- Middle correspondence agent: translate the oracle description into Lean-facing definitions and a concise proof map.
- Lower natural-language architect: propose one candidate circuit and write the expected block-entry proof.
- Lower Lean worker: implement exactly one ready certificate leaf.
- Lower verifier: run exact finite checks only when their failure is a necessary contradiction to the Lean goal.
- Reviewer: reject hidden assumptions, wrong metric ordering, and unverified candidates in plots.

## First Command Sketch

\`\`\`bash
export QBE_REPORT_LANGUAGE="${lang}"
python3 tools/qbe.py new-task "${title}" \\
  --mode "${mode.value}" \\
  --source "web task packet" \\
  --target-lean "TBD"
python3 tools/qbe.py run-cycle "${title}" --upper-panel --middle-panel
# Optional after saving the JSON above as agent-profiles/${title}.json:
python3 tools/qbe.py sleep-run "${title}" \\
  --cycles 2 \\
  --lower-count 3 \\
  --parallel-lower \\
  --agent-profile "${title}.json" \\
  --execute \\
  --check-each-cycle
\`\`\`
`;
  packet.textContent = md;
}

async function copyPacket() {
  await navigator.clipboard.writeText(packet.textContent);
  copyStatus.textContent = "Copied";
  window.setTimeout(() => {
    copyStatus.textContent = "";
  }, 1600);
}

function downloadPacket() {
  const blob = new Blob([packet.textContent], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const safeName = (taskName.value.trim() || "abeis-task")
    .replace(/[^a-z0-9._-]+/gi, "-")
    .replace(/^-+|-+$/g, "");
  a.href = url;
  a.download = `${safeName || "abeis-task"}.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

languagePreset.addEventListener("change", () => {
  languageCustom.disabled = languagePreset.value !== "custom";
  buildPacket();
});

[
  taskName,
  mode,
  languageCustom,
  oracleDescription,
  normalizer,
  projector,
  baseline,
  constraints,
  upperBackend,
  middleBackend,
  lower1Backend,
  lower2Backend,
  lower3Backend,
  reviewerBackend,
].forEach((element) => {
  element.addEventListener("input", buildPacket);
  element.addEventListener("change", buildPacket);
});

document.getElementById("buildPacket").addEventListener("click", buildPacket);
document.getElementById("copyPacket").addEventListener("click", copyPacket);
document.getElementById("downloadPacket").addEventListener("click", downloadPacket);

buildPacket();
